### ISSUE TITLE
Usage of drawin compose 

### ISSUE THREAD

**Issue by TaehoonLeee** [arkivanov/Decompose#121]
Hi, can you help me? 

I tried to run ./gradlew iosDeployIPhone12Debug

but it threw the following error

> Field 'dataPathSize' is required for type with serial name 'org.jetbrains.compose.experimental.uikit.internal.DeviceData', but it was missing

**Comment by arkivanov** [comment]
Hello. Could you explain where do you run that command? Do you have a reproducer?

**Comment by TaehoonLeee** [comment]
I solve this issue by updating xcode. Thanks for reply!

**Comment by arkivanov** [comment]
Thanks for sharing the solution! May be useful for others.
