### ISSUE TITLE
Navigation does not work on chrome ios

### ISSUE THREAD

**Issue by amuna** [arkivanov/Decompose#123]
Only occurs on chrome for mobile ios devices. After debugging, it appears the issue is that routerState.activeChild.instance does not update after child is created.

//This code does not get executed.
```
Crossfade(
            target = routerState.activeChild.instance, 
            attrs = {
                style {
                    width(100.percent)
                    height(100.percent)
                    position(Position.Relative)
                    left(0.px)
                    top(0.px)
                }
            }
        ) { child ->
            when (child) {
                is Nav.Child.Splash -> Splash(component)
                is Nav.Child.Inbox -> ChatUI(component)
                is Nav.Child.Home -> Home(component)
                is Nav.Child.HomePage -> HomePage(component)
        }
    }
`

**Comment by arkivanov** [comment]
It's not clear where `Crossfade` comes from? Also `routerState` is `Value` and should be subscribed in order to receive updates. If you are using React, then here is an example - https://github.com/arkivanov/Decompose/blob/d112f923a417b2923bf5478954728acfaef7d8cb/sample/shared/shared/src/jsMain/kotlin/com/arkivanov/sample/shared/Utils.kt#L12

**Comment by amuna** [comment]
routerState is located in navComponent. We are using the same pattern as ToDoApp. Here is the fill code for that file. This code works well for all other browsers. Does this help with the problem?

```
@ExperimentalComposeWebApi
@Composable
fun TodoRootUi(component: NavComponent) {
        val routerState by component.routerState.subscribeAsState()

        Crossfade(
            target = routerState.activeChild.instance,
            attrs = {
                style {
                    width(100.percent)
                    height(100.percent)
                    position(Position.Relative)
                    left(0.px)
                    top(0.px)
                }
            }
        ) { child ->
            when (child) {
                is Nav.Child.Splash -> Splash(component)
                is Nav.Child.Inbox -> ChatUI(component)
                is Nav.Child.Home -> Home(component)
                is Nav.Child.HomePage -> HomePage(component)
            }
        }
    }


```

**Comment by arkivanov** [comment]
Yeah, not it's clear. I will try to debug.

**Comment by arkivanov** [comment]
@amuna I tried the todoapp sample on iPad with Chrome browser, works fine - so I couldn't reproduce the issue. Could you please try to minimize the issue? This also may be either Compose or Kotlin bug. 

Please use the following function with logs instead of the one provided by Decompose, and post logs here.

```kotlin
@Composable
fun <T : Any> Value<T>.subscribeAsStateDebug(): State<T> {
    println("subscribeAsState")
    val state = remember(this) { mutableStateOf(value) }

    DisposableEffect(this) {
        val observer: ValueObserver<T> = {
            println("New state: $it")    
            state.value = it 
        }

        println("Subscribe")
        subscribe(observer)

        onDispose {
            println("Dispose")
            unsubscribe(observer)
        }
    }

    return state
}
```

Also please add logs here:

```kotlin
@ExperimentalComposeWebApi
@Composable
fun TodoRootUi(component: NavComponent) {
        val routerState by component.routerState.subscribeAsStateDebug()

        println("New routerState: $routerState)
        Crossfade(
            ...
        ) { child ->
            ...
        }
    }
```

Also please make sure that the `Router` is actually triggered, e.g. `router.push()` or similar is called. Thanks!

**Comment by amuna** [comment]
Sorry for the late reply. Attached are the logs for when the app starts.

![IMG-0284](https://user-images.githubusercontent.com/25041693/174504841-c36e9aef-3e03-4f6b-873b-95073f6c7955.PNG)


And here are the logs for when we press the button.
![IMG-0285](https://user-images.githubusercontent.com/25041693/174504824-631985ad-c346-4b50-993a-d8b59aaa5f6a.PNG)
)

The website is called iknowem.com where the issue observed.

Here is confirmation that the router was triggered:

```
private fun replaceOrPushConfig(config: Config) {
        val activeConfig = router.activeChild.configuration
        if ( activeConfig is Config.Splash || activeConfig is Config.Signup) {
            println("%%%%%%%% IF BLOCK")
            println(config.route)
            router.replaceCurrent(config)
            getStackData("10")
        } else {
            println("%%%%%%%% ELSE BLOCK")
            router.push(config)
            getStackData("20")
        }
    }
```

**Comment by arkivanov** [comment]
Thanks for the logs! If I understand it correctly, the Composable function is recomposed with the new router state after `replaceCurrent(SignUp)`. Of the screen is still not updated, then looks like the issue is with `Crossfade`. Could you please try without `Crossfade`? Just switch children directly.

**Comment by amuna** [comment]
I think there is an issue when router.push(SignUp) is called because the line below does not get executed (getStackData("20")). This should print 20: getData() after router.push(SignUp) but its not seen. Please see my previous comment

```
    private fun getStackData(num: String = "1") {
        println("$num: getData()")
        println("backstack-size: ${router.state.value.backStack.size}")
        println("ActiveChild: ${router.state.value.activeChild.instance::class.simpleName}")
        router.state.value.backStack.forEach {
            println("Backstack: ${it.configuration::class.simpleName}")
        }
    }

```
Here is the router and createChild method

```
private val router: Router<Config, Nav.Child> =
        router(
            initialStack = { getInitialStack(deepLink) },
            handleBackButton = true,
            childFactory = ::createChild
        )

    private fun createChild(config: Config, componentContext: ComponentContext): Nav.Child {
        println("?????????? ${config.route}")
        println(config::class.simpleName)
        return when (config) {
            is Config.Splash -> Nav.Child.Splash()
            is Config.HomePage -> Nav.Child.HomePage()
            is Config.Signup -> {
                println("%%%%%%%% 3")
                if (extra != null) {            //extra is static variable called from another class
                    println("%%%%%%%% 3.1")
                    Nav.Child.Signup(true). // I suspect the issue occurs here or around here. 
                    //I'm not able to add logs here
                } else {
                    println("%%%%%%%% 3.2")
                    Nav.Child.Signup()
                }
            }
        }
    }


interface Nav {
    val routerState: Value<RouterState<*, Any>>

    sealed class Child {
        class Splash : Child()
        class HomePage : Child()
        class Signup(val influencerSignup: Boolean = false) : Child()
    }
}
```

**Comment by arkivanov** [comment]
Thanks for the additional details. Now it looks like `router.push(config)` call doesn't return. Are there any errors or exceptions in the console? Would you be able to attach a reproducer project, so I could try it locally on my iOS device?

**Comment by amuna** [comment]
No errors or exceptions are seen. What exactly do you mean by reproducer project?

**Comment by arkivanov** [comment]
@amuna It would be very helpful to see a small project that reproduces the issue. You could strip off all the unrelated details from your project, but keep the issue reproducible. I suspect there is something specific in the code you wrote, that causes the issue to happen. At the moment, this looks like yet another bug in Kotlin/JS.

**Comment by arkivanov** [comment]
I have tried one more time to reproduce the issue with the provided pieces of code with - couldn't reproduce. Either the issue is not reproducible at all on my iPad with Chrome browser, or there is something else in your project that causes the issue. A reproducer would be very helpful.

**Comment by amuna** [comment]
I will send one shortly.

**Comment by amuna** [comment]
> I have tried one more time to reproduce the issue with the provided pieces of code with - couldn't reproduce. Either the issue is not reproducible at all on my iPad with Chrome browser, or there is something else in your project that causes the issue. A reproducer would be very helpful.

I've added you as collaborator to the sampler project. Can you please confirm if you got it?

**Comment by arkivanov** [comment]
Thanks, I have received the invitation and will check the reproducer soon

**Comment by arkivanov** [comment]
@amuna Thanks again for the reproducer! I was able to reproduce the issue and find the cause. There seems to be an issue in `DefaultWebHistoryController`, which is used for managing the Web browser history. It uses [History.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState), which is apparently [broken](https://stackoverflow.com/a/47289493/10413396) in Chrome for iOS.

I will need to think about possible solution or workaround, or maybe just disable it for Chrome for iOS. Meantime, please do let me know if you have any ideas or houghts.

**Comment by amuna** [comment]
Any estimation when the fix will be available?

**Comment by arkivanov** [comment]
At the moment I doubt if there is any possible fix - the essential API looks broken in Chrome for iOS. I will follow-up in the coming days. Meantime you can try to detect the "Chrome on iOS" browser, and not pass `DefaultWebHistoryController` into `NavComponent`.

**Comment by amuna** [comment]
Thank you for the quick responses. Another issue I've observed is that when the forward button is pressed, it does not go to the correct screen. It will show a blank white screen instead. Can you look into that issue as well? It should be reproducible on the reproducer. I've observed that it occurs on desktop

**Comment by arkivanov** [comment]
@amuna Is it only on Chrome for iOS as well? If so, then I think this is also due to the mentioned bug in Chrome.

**Comment by amuna** [comment]
@arkivanov, I tried again. On chrome, it stays on the same page when pressing forward. On firefox and safari, it will also stay on the same page. But if you click on second page, go back and then click forward, then its working fine. But on the first page it doesn't work. 

Example. On our app. Click on Fan button. Press back. Then press forward. It does not work. But if you then press Influencer button from home page, press back, press forward, it then works

**Comment by amuna** [comment]
^This test was done on desktop

**Comment by arkivanov** [comment]
@amuna I have checked the second issue - basically, you should implement `getConfiguration` function properly. This is required for `DefaultWebHistoryController` so it could recreated configurations for each path. Please see an [example](https://github.com/arkivanov/Decompose/blob/d112f923a417b2923bf5478954728acfaef7d8cb/sample/shared/shared/src/commonMain/kotlin/com/arkivanov/sample/shared/root/RootComponent.kt#L83).

Something as follows, just an example for those two configurations, but you need all of them:

```kotlin
        webHistoryController?.attach(
            router = router,
            getPath = { "/${it.route}" },
            getConfiguration = {
                when (it) {
                    "/Signup" -> Config.Signup()
                    "/SignUp" -> Config.HomePage()
                    else -> error("Unknown route: $it")
                }
            }
        )
```

Please also mind some [limitations and a corner case](https://arkivanov.github.io/Decompose/router/browser-history/#corner-cases) (not affecting this particular case, but still good to be aware of).

**Comment by amuna** [comment]
> At the moment I doubt if there is any possible fix - the essential API looks broken in Chrome for iOS. I will follow-up in the coming days. Meantime you can try to detect the "Chrome on iOS" browser, and not pass `DefaultWebHistoryController` into `NavComponent`.

I did some research and from what I found is that there is no reliable way to determine if the browser on ios is chrome. [I've posted this question here](https://stackoverflow.com/questions/72716791/javascript-determine-what-browser-is-being-used-on-iphone-devices?noredirect=1#comment128444730_72716791) but I don't think there is a solution for this. Do you have any other ideas?

**Comment by arkivanov** [comment]
No ideas yet, I have asked a couple of folks about it, and I am planning to dig the issue in the coming days.

**Comment by amuna** [comment]
I'm able to detect chrome on ios using [this](https://stackoverflow.com/questions/13807810/ios-chrome-detection). Note I haven't done thorough testing on this but navigation is now working when we don't attach `DefaultWebHistoryController` into `NavComponent `.

**Comment by arkivanov** [comment]
Thanks for the information! This should be helpful.

**Comment by arkivanov** [comment]
Thanks again for raising this issue! After some investigation I realised that the issue is actually in `DefaultWebHistoryController`, more specifically in the way how it manages the web history. It places nodes with mutable pointers in the history stack, and modifies the pointers when the router stack is changed. For some reason Chrome for iOS doesn't like such manipulations, and stucks.

The whole web history API in Decompose is experimental, so it's good that we find bugs on early stages. I will need to find another way of managing the web history inside `DefaultWebHistoryController`, there are possible API changes as well. I will provide updates here.

**Comment by amuna** [comment]
Any estimation when it will be available?

**Comment by arkivanov** [comment]
Hopefully by the end of the week.

**Comment by amuna** [comment]
@arkivanov, any estimation when this fix will be released officially and can be used?

**Comment by arkivanov** [comment]
I will release a new version today.

**Comment by arkivanov** [comment]
Decompose [v0.7.0](https://github.com/arkivanov/Decompose/releases/tag/0.7.0) is released, this should work now.
