### ISSUE TITLE
Problem with configurations containing 3rd-party non-parcelable classes.

### ISSUE THREAD

**Issue by evjava** [arkivanov/Decompose#133]
Is it possible to use `arrow.core.Either` (or other classes from 3rd-party multiplatform libraries which isn't inherit Parcelable / Serializable) as part of configuration class?

Context: I want to store (inside some of configurations) something like `Either<TemporaryView, String>`, where the `.right()` is for an id of DbView (I don't want to store it inside configuration) and `.left()` is for a temporary view (which can be saved).

Right now my configuration looks like this:
```
// main module
sealed class Screen : Parcelable {
    @Parcelize
    data class Notes(val filter: NotesFilterInfo) : Screen()
    ...
}

// shared module without access to parcelable
data class NotesFilterInfo(
    @Serializable(with = EitherSerializer::class)
    tempOrId: Either<NotesFilter, String>
) : java.io.Serializable

@Serializable
data class NotesFilter(val id: String, val tags: List<String>) : java.io.Serializable
```

And it fails when activity paused:
```
 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = NotesFilterInfo)
        at android.os.Parcel.writeSerializable(Parcel.java:1833)
        at NotesFilterInfo.writeToParcel(Unknown Source:16)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at com.arkivanov.essenty.parcelable.AndroidParcelableContainer.writeToParcel(AndroidParcelableContainer.kt:32)
        ...
     Caused by: java.io.NotSerializableException: arrow.core.Either$Right
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at android.os.Parcel.writeSerializable(Parcel.java:1828)
        	... 51 more
```

Don't sure how to solve this problem, so I have some sub-questions:
1. Is it actully enough to implement Serializable to have Parcelable? (`NotesFilterInfo` is contained inside shared module without access to Parcelable)
2. Is it possible to define custom router with serializable configuration? (my configurations isn't big and Parcelable implementation probably hasn't perfomance gain comparing to Serializable implementation)

**Comment by arkivanov** [comment]
Looks like Either doesn't implement Serializable interface. You should be able to update Essenty library to 0.4.1 and use [custom parcelers](https://github.com/arkivanov/Essenty#custom-parcelers).

**Comment by evjava** [comment]
1. What about second question? (implementing router Serializable configuration instead of Parcelable)
2. Do I understand correctly, that it's impossible to implement generic `Parceler` for all `Either<A, B>`? (Type parameters isn't allowed for objects)

**Comment by arkivanov** [comment]
Sure, here are the answers.

> What about second question? (implementing router Serializable configuration instead of Parcelable)

This is not possible, unfortunately. Decompose relies on Parcelable + Parcelize. This approach is scalable, e.g. it could be applied to iOS if needed in the future.

> Do I understand correctly, that it's impossible to implement generic Parceler for all Either<A, B>? (Type parameters isn't allowed for objects)

First of all, your `NotesFilterInfo` implements `Serializable` incorrectly - it contains `Either` which is not `Serializable`. So `NotesFilterInfo` can not be serialized correctly. You can try to manually serialize Either, please see the [Serializable docs](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html).
 
Generic parameters seems not allowed indeed. But actually you don't need to write `Parceler` for `Either`. You can do the following:

```kotlin
object NotesFilterInfoParceler : Parceler<NotesFilterInfo> {
    override fun create(parcel: Parcel): NotesFilterInfo =
        NotesFilterInfo(
            tempOrId = when (parcel.readInt()) {
                0 -> Either.Left(parcel.readSerializable() as NotesFilter)
                1 -> Either.Right(requireNotNull(parcel.readString()))
                else -> error("NotesFilterInfo parcelable is corrupted")
            }
        )

    override fun NotesFilterInfo.write(parcel: Parcel, flags: Int) {
        when (tempOrId) {
            is Either.Left -> {
                parcel.writeInt(0)
                parcel.writeSerializable(tempOrId.value)
            }
            is Either.Right -> {
                parcel.writeInt(1)
                parcel.writeString(tempOrId.value)
            }
        }.let {}
    }
}

// Usage

sealed class Screen : Parcelable {
    @Parcelize
    data class Notes(val filter: @WriteWith<NotesFilterInfoParceler> NotesFilterInfo) : Screen()
}
```

**Comment by evjava** [comment]
Great, thanks for detailed answer!

**Comment by evjava** [comment]
Finally found pretty simple solution: it's enough to wrap Screen in `Parcelable` class:

```kotlin
@Serializable
sealed class Screen : java.io.Serializable {
  @Serializable data class Notes(..) : Screen()
  @Serializable data class Settings(..) : Screen()
}

@Parcelize
data class ScreenWrapper(val screen: Screen) : Parcelable
```

And then pass `ScreenWrapper` to the router. `Parcelable` classes with `Serializable` fields can be "parceled" without problems.

**Comment by arkivanov** [comment]
@evjava This looks quite the same as in the original code snippet in the first message.

```kotlin
sealed class Screen : Parcelable {
    @Parcelize
    data class Notes(val filter: NotesFilterInfo) : Screen()
}

data class NotesFilterInfo(
    @Serializable(with = EitherSerializer::class)
    tempOrId: Either<NotesFilter, String>
) : java.io.Serializable
```

There we also have "parcelable classes with Serializable fields" - `Screen.Notes` is a parcelable class with serializable field `NotesFilterInfo`. The original issue is because serializable classes can't contain non-serializable things, e.g. `Either` can't be serialized.

**Comment by evjava** [comment]
Indeed._.

Sorry, replaced `Either` with my own implementation and forgot about it.
