### ISSUE TITLE
Navigation doesn't work on consecutive windows with ChildStack

### ISSUE THREAD

**Issue by russellbanks** [arkivanov/Decompose#146]
### Bug Description

In my Compose for Desktop [app](https://github.com/russellbanks/HashHash), I have a way of "restarting" the app, which is done through creating a new window with the same data and closing the previous window. However, since migrating `Router` to `Child Stack`, the navigation doesn't seem to persist between multiple windows, despite it working with the now deprecated `Router`. The commit that migrated this is below, but there doesn't seem to be anything code-side that would have caused this as most of the migration was renaming.

[Child Stack migration commit](https://github.com/russellbanks/HashHash/commit/14eeddcce7c25feaf41e4ad559af9eca16fd274c)

#### Before migration:

https://user-images.githubusercontent.com/74878137/179429864-7f3d8b74-daaa-45ed-a891-6e8f4cefecbb.mp4

#### After migration:

https://user-images.githubusercontent.com/74878137/179429040-ffff5153-6c89-4f29-86af-32a464fce9d8.mp4

### Platform Info

Decompose Version: 0.8.0

Operating System: Windows 11

**Comment by arkivanov** [comment]
I have checked the code of your app. The `Root` component is a singleton, the same instance is used across windows. However its lifecycle is being controlled by `LifecycleController` composable function, that destroys the lifecycle when the first window is gone. You should either control the root lifecycle manually, e.g. just call `lifecycle.resume` somewhere. Or scope your `Root` component in each window (separate instances for each window), not in the entire app.

**Comment by arkivanov** [comment]
So basically the new `Child Stack` now unsubscribes from `StackNavigation` on destroy, but the old `Router` doesn't (there is no such a concept in the old `Router`). The new `Child Stack` uncovered an issue with lifecycle in the app.

**Comment by russellbanks** [comment]
Thank you so much for finding out the root cause of this :)

I've fixed this in my app by controlling the lifecycle a bit more manually. I'm not sure whether it's the best means but rather than `LifecycleController` calling `destroy` on dispose, I've altered it to call `stop` (so that it can be resumed when the new window is opened), and then `lifecycle.destroy()` is called when the application itself is fully closed.
