### ISSUE TITLE
Logo wanted!

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#174]
Decompose needs its own logo. The logo should express the main purpose of the library:

> Decompose breaks the code down into small and independent components and organizes them into trees.

> Navigation.

Something like a few coloured nodes connected into a tree, some of the nodes are grayed out (inactive). That's just my imagination. :-)

**Comment by malliaridis** [comment]
I am not creative nor a designer, so show mercy with my attempts. 😂 I thought I give it a try and see what will come out.

I hope I can give with those initial ideas some inspiration for actual designers. Can't wait to see the final logo of Decompose 😄 

I tried to make some use of all words, including "breaks the code down" (zero and one as the background represent the code), "small and independent components" (smaller forms with different colors) and "organizes them into trees"  as well as navigation (connections between the components and tree hierarchy).

_P.S. the first layer was a failed attempt to literally "break" the numbers into structured (as a tree) components._

<img width="652" alt="Screenshot 2022-08-09 at 22 51 22" src="https://user-images.githubusercontent.com/33470669/183749357-f42533dc-20ff-4689-bf64-7a1b1038a67d.png">

**Comment by arkivanov** [comment]
Thanks! I see having a tree of nodes as a right direction. Though I would kinda prefer a flat "material" style, with circle shapes and different colours - blue, yellow, green, red.

Here is something I had in mind a while ago.

<img src="https://user-images.githubusercontent.com/26204457/183961203-0d7ce89d-b016-438b-a117-a785f2dfe2cd.png" width="256" >

**Comment by malliaridis** [comment]
This looks actually pretty good and simple. I would probably go for a bit larger circles, so when the logo scales down, the colors are not getting lost because of the small size.

**Comment by plusmobileapps** [comment]
what about a bloc inside a bloc?

![decompose.png](https://user-images.githubusercontent.com/31364841/184473373-096518d3-1302-488a-a85d-0b8f8d4de3ed.png)

**Comment by YektaDev** [comment]
I gave it a shot.
---
![decompose](https://user-images.githubusercontent.com/22149430/187015734-4d485a62-7d9d-44eb-89a4-5d71a7f77687.png)
---
![decompose_outlined](https://user-images.githubusercontent.com/22149430/187015743-99c2dea5-62ff-4727-91bf-0bf739b1e57d.png)

**Comment by arkivanov** [comment]
@YektaDev Thanks, nice one! That red route is like an active sub-tree, and blue nodes are inactive? Looks awesome! Would it be possible for you to provide square assets as well, without the title?

**Comment by YektaDev** [comment]
@arkivanov Exactly, a minimal component tree with an active sub-tree. Here are the square assets (open in a new tab to see in full size):
<p align="center">
<img width="256" src="https://user-images.githubusercontent.com/22149430/187031849-2d0a800c-850a-4fd2-9a67-1fb0b5431b0e.png"/>
<img width="32"/>
<img width="256" src="https://user-images.githubusercontent.com/22149430/187031852-2b47f913-9e5b-4359-90f2-85227fbae1df.png"/>
<br />
<img width="256" src="https://user-images.githubusercontent.com/22149430/187031855-aa065e2b-57b1-4bd6-aa91-0aabaebff888.png"/>
<img width="32"/>
<img width="256" src="https://user-images.githubusercontent.com/22149430/187031859-1bdded81-13ad-475a-9a3a-262bf5c5f1c4.png"/>
</p>

**Comment by arkivanov** [comment]
@YektaDev Thank you! I'm going to set this as a logo of the project. Would it be possible for you to also provide a source? So I could cut different sizes later if needed.

**Comment by YektaDev** [comment]
Glad to help. The files aren't in vector format; but I chose the sizes big enough to prevent the need of scaling up. 
[Decompose_PSD.zip](https://github.com/arkivanov/Decompose/files/9439711/Decompose_PSD.zip)

**Comment by malliaridis** [comment]
Allow me then @YektaDev to provide the logo as SVG (with the option to add background or change the colors).
[decompose-logo-svg.zip](https://github.com/arkivanov/Decompose/files/9439778/decompose-logo-svg.zip)

**Comment by arkivanov** [comment]
Big thanks @YektaDev and @malliaridis! I have uploaded all assets under [/docs/media/logo](https://github.com/arkivanov/Decompose/tree/master/docs/media/logo) folder. I have also added the logo to the project's [readme](https://github.com/arkivanov/Decompose), and the [documentation website](https://arkivanov.github.io/Decompose/).
