### ISSUE TITLE
Extension for Compose Dependencies Not Being Added

### ISSUE THREAD

**Issue by hompiler** [arkivanov/Decompose#175]
every time I try to use any compose extension either jetpack or JetBrains it's not showing

**Comment by arkivanov** [comment]
Could you please share your Gradle configuration? And also could please elaborate what exactly not showing?

**Comment by hompiler** [comment]
``` 
val commonMain by getting {
            dependencies {
                // other dep
                implementation("com.arkivanov.decompose:decompose:1.0.0-alpha-01")
                implementation("com.arkivanov.decompose:extensions-compose-jetbrains:1.2.0-alpha01-dev753")
            }
}
```
anything in the extension documentation is not resolving like `Value<T>.subscribeAsState()` or `Children()`
https://arkivanov.github.io/Decompose/extensions/compose/

**Comment by hompiler** [comment]
the whole package
import com.arkivanov.decompose.extensions
is not resolving when i try to import it manually

**Comment by arkivanov** [comment]
The version you specified for `extensions-compose-jetbrains` is incorrect. All modules under `com.arkivanov.decompose` group should have the same version, in this particular case it should be `1.0.0-alpha-01`. Could you please try changing the version?

**Comment by hompiler** [comment]
Yeah, it's working now.
I misunderstood the release details where it says: `JetBrains Compose: 1.2.0-alpha01-dev753`. I thought that means that 1.2.0 is the compatible version with this decompose release.
https://github.com/arkivanov/Decompose/releases/tag/1.0.0-alpha-01
Sorry for that.

But I've some difficulties understanding the new stack navigation API. I'd be grateful if you can provide any sample using it or an article as I couldn't find any.

Thank you.

**Comment by arkivanov** [comment]
Yeah, that just means that Decompose extensions `1.0.0-alpha-01` depend on JB Compose `1.2.0-alpha01-dev753`.

Re: stack navigation - you can check samples:

Bottom bar navigation: https://github.com/arkivanov/Decompose/blob/master/sample/shared/shared/src/commonMain/kotlin/com/arkivanov/sample/shared/root/RootComponent.kt
Stack navigation: https://github.com/arkivanov/Decompose/blob/master/sample/shared/shared/src/commonMain/kotlin/com/arkivanov/sample/shared/dynamicfeatures/DynamicFeaturesComponent.kt
