### ISSUE TITLE
"Used by" list

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#187]
It would be good to have a list of companies/users/projects where Decompose is used. I suggest to stick to the following format, but feel free to omit/add/modify any details. ❤️

Project name: \<project name\>
Project type: production/pet/sample
Company name: personal/\<company name\>
Supported platforms: Android, JVM, Web, iOS, macOS, etc.
Link (an open source repository or a web site): \<link\>

**Comment by moffpage** [comment]
Project name: Vlife
Description: Vlife is an app for motorists and everyone who likes to get Points and privileges for their usual purchases: sign up for a car wash, make purchases in installments in Market, pay for utilities, take out insurance and accumulate Points with our partners.
Company Name: LLC "GRAND ERA"
Project type: Production
Supported targets: currently only Android
You can install in in Google Play Store: https://play.google.com/store/apps/details?id=kz.vlife.grandera

**Comment by a-blekot** [comment]
Project name: Memorize shlokas (Sanskrit verses study)
Project type: production
Company name: personal (Aleksey Blekot)
Supported platforms: Android, iOS, Mac M1 😊
[PlayStore](http://play.google.com/store/apps/details?id=com.a_blekot.memorize_shloka)
[AppStore](https://apps.apple.com/app/id6443863948)
[GitHub](https://github.com/a-blekot/memorize_shloka)

**Comment by egorikftp** [comment]
![image](https://user-images.githubusercontent.com/16294951/193465838-50554b56-3b06-4e01-8068-df9e0aa5495f.png)

Project name: За рулем (Гродно)
Description: Application helps to agregate actual situation on the roads
Project type: production
Company name: personal
Supported platforms: Android
Link (an open source repository or a web site): [Google Play](https://play.google.com/store/apps/details?id=com.egoriku.grodnoroads) [Github](https://github.com/egorikftp/GrodnoRoads)

**Comment by brandonpollack23** [comment]
Project name: Before You Die
Project type: Personal Task Managment/ TODO list software with blocking/blocked by feature
Company name: personal
Supported platforms: Android, JVM, Web, (iOS when UI is done).
Link (an open source repository or a web site): https://github.com/brandonpollack23/before_you_die

**Comment by ashdavies** [comment]
Project name: Playground
Project type: pet
Platforms: Android, JVM, Server
Link: [ashdavies/playground](https://github.com/ashdavies/playground)

**Comment by oianmol** [comment]
Project name: Slack Compose Kotlin Multiplatform Clone with gRPC
Project type: pet
Company name: personal
Supported platforms: Android, JVM, iOS
Link : https://github.com/oianmol/SlackComposeMultiplatform

**Comment by azlekov** [comment]
Project name: Dodi
Description: Simplify access management of short-term rentals
Project type: pet
Company name: DODI Smart
Supported platforms: Android, iOS
Link: https://dodi.li

**Comment by t1r** [comment]
Project name: Compose Theme Builder
Project type: pet
Company name: personal
Supported platforms: Android, JVM, (iOS in future)
Link: [ComposeThemeBuilder](https://github.com/t1r/ComposeThemeBuilder)

**Comment by blvckcoded** [comment]
Project name: DodoForMastodon
Project type: production/pet
Company name: open source, led by Androiddev-social community
Supported platforms: Android, iOS, and Desktop JVM
Link: https://github.com/AndroidDev-social/DodoForMastodon

**Comment by xxfast** [comment]
Project name: NYTimes-KMP
Project type: sample
Company name: personal
Supported platforms: Android, JVM, iOS, and Web
Link: https://github.com/xxfast/NYTimes-KMP

**Comment by MohamedRejeb** [comment]
Project name: Pokedex
Project type: sample
Company name: personal
Supported platforms: Android, JVM, iOS
Link: https://github.com/M0Coding/Pokedex
