### ISSUE TITLE
Accessing non-final property lifecycle in constructor

### ISSUE THREAD

**Issue by YektaDev** [arkivanov/Decompose#192]
I was attempting to do something similar to [this example](https://arkivanov.github.io/Decompose/component/lifecycle/#usage-example), which led to the following warning:
```kotlin
class Foo(context: ComponentContext) : ComponentContext by context {
    private val screenLifecycle = object : Lifecycle.Callbacks {
        override fun onCreate() { /*...*/ }
        override fun onStart() { /*...*/ }
        override fun onResume() { /*...*/ }
        override fun onPause() { /*...*/ }
        override fun onStop() { /*...*/ }
        override fun onDestroy() { /*...*/ }
    }

    init {
        lifecycle.subscribe(screenLifecycle)
        //^^^^^^^
        //Accessing non-final property lifecycle in constructor 
    }
    // ...
}
```
Since I tried a simple logging inside `onCreate` of `screenLifecycle` and nothing was shown, I wanted to see whether this warning is the reason or it's somehow related to another issue.

**Comment by arkivanov** [comment]
This shouldn't be the case because `Foo` class is final. Are you using the [All-open](https://kotlinlang.org/docs/all-open-plugin.html) plugin? If so, I recommend to avoid using it. Otherwise, you can access lifecycle in the `init` section as `context.lifecycle`.

**Comment by YektaDev** [comment]
Exactly as described! `Foo` is kind of a base class for screens. I tried using `context.lifecycle.subscribe(screenLifecycle)` and the warning disappeared, but it still does nothing on those events. So it's not possible to subscribe to the lifecycle from a base class?

**Comment by arkivanov** [comment]
It should be possible. Could you share a reproducer code?

**Comment by YektaDev** [comment]
Current sample is part of something bigger with custom component context and other stuff; but I guess just adding `abstract` to the above `Foo` and extending it from another class should suffice for testing whether the `onCreate` as an example works or not.

**Comment by arkivanov** [comment]
I have just checked, the following code prints "onCreate".

```kotlin
abstract class AbstractComponent(context: ComponentContext) : ComponentContext by context {
    private val screenLifecycle = object : Lifecycle.Callbacks {
        override fun onCreate() { println("onCreate") }
        override fun onStart() { /*...*/ }
        override fun onResume() { /*...*/ }
        override fun onPause() { /*...*/ }
        override fun onStop() { /*...*/ }
        override fun onDestroy() { /*...*/ }
    }

    init {
        context.lifecycle.subscribe(screenLifecycle)
    }
}

class RootComponent(context: ComponentContext) : AbstractComponent(context)

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        RootComponent(
            context = defaultComponentContext(),
        )
}
```

Please make sure that you are passing `ComponentContext` correctly, and that you drive the lifecycle correctly. On Android it is advised to create the `Lifecycle` using extensions functions, e.g. `defaultComponentContext()`. On other platforms you should use `LifecycleRegistry` and drive the `Lifecycle` manually.

**Comment by YektaDev** [comment]
The code you tested is exacly picturing how I did this. So the problem lies elsewhere; most likely in how I implemented the custom context, or probably the way I passed the context, as you mentioned. I'll soon check these places haunting the bug. Thanks a lot for your time and effort!

**Comment by arkivanov** [comment]
No problem! If you still believe that something is not working properly, it would be useful if you provide a minimal reproducer code.
