### ISSUE TITLE
official doc and sample are outdate, please update it.

### ISSUE THREAD

**Issue by MansonLuo** [arkivanov/Decompose#196]

**Comment by arkivanov** [comment]
Could you point on where you found the outdated docs?

**Comment by MansonLuo** [comment]
https://github.com/theapache64/decompose-desktop-example

this project use decode version of 0.4.0,but current version is 1.0.0.maybe other sample isnt same.
this sample is only one that is simple to me, cause it's for compose desktop.
thanks, could you please provide more sample only on compose for desktop?

**Comment by arkivanov** [comment]
Indeed, that sample is outdated. Thanks for raising. @theapache64 Would you like to update the sample on your own? Or do you want me to update it?

**Comment by theapache64** [comment]
I can do that before Wednesday

**Comment by arkivanov** [comment]
Thanks @theapache64 ! Please do let me know if you have any questions or issues.

**Comment by theapache64** [comment]
@arkivanov Migration [PR](https://github.com/theapache64/decompose-desktop-example/pull/3) ready. Can you please review?

**Comment by arkivanov** [comment]
The sample is now updated.
