### ISSUE TITLE
Add `collectAsStateWithLifecycle` to Compose extensions

### ISSUE THREAD

**Issue by YektaDev** [arkivanov/Decompose#210]
Since Decompose provides a multi-platform Lifecycle API, it might be useful to also have the `collectAsStateWithLifecycle` extension for Compose which uses this Lifecycle API to handle collecting `StateFlow`s, probably with a similar functionality to [`collectAsStateWithLifecycle`](https://github.com/androidx/androidx/blob/eb79c4c8605121203218d5d2589e2d1e6f77ba76/lifecycle/lifecycle-runtime-compose/src/main/java/androidx/lifecycle/compose/FlowExt.kt#L168) provided for Android lifecycle and Jetpack Compose. Lastly, as @arkivanov [mentioned](https://twitter.com/arkann1985/status/1572870506994442241), there's also something to consider, which is "...In Decompose, components are already lifecycle-aware.".

[🧾 The sample implementation gist](https://gist.github.com/arkivanov/01b9599b329e8809f39f83c264694e30) - [🐦 The tweet](https://twitter.com/arkann1985/status/1572618055414587393)

P.S. I would also recommend deciding about whether or not to switch to `Dispatchers.Main.immediate` context before collecting the `StateFlow`, if the decision was to add the extension.

**Comment by arkivanov** [comment]
Thanks for raising it, I will investigate the possibility. There are some concerns currently:

1. Since components are already lifecycle-aware, it should be possible to just avoid emitting new states while in the background. So there would be no need to collect with lifecycle on the UI side.
2. Currently none of the modules depend on coroutines directly. This would require adding dependency the dependency.

**Comment by aartikov** [comment]
@arkivanov 
>Since components are already lifecycle-aware, it should be possible to just avoid emitting new states while in the background. So there would be no need to collect with lifecycle on the UI side.

Totally agree.
It is supposed that a component is independent from UI. `collectAsStateWithLifecycle` breaks this rule. UI implicitly changes the behaviour of a component by the fact of displaying it. Such component is harder to debug, harder to test and so on.

**Comment by arkivanov** [comment]
There was a discussion about `Flow.flowWithLifecycle` - https://github.com/arkivanov/Essenty/discussions/71. It should address this issue as well. Not sure if it is going to be added into the library, but there is a code to copy-paste. Closing this one for now.
