### ISSUE TITLE
Update Kotlin to `1.7.20`

### ISSUE THREAD

**Issue by YektaDev** [arkivanov/Decompose#216]
The Kotlin 1.7.20 release [is out](https://blog.jetbrains.com/kotlin/2022/09/kotlin-1-7-20-released/)!

**Comment by arkivanov** [comment]
Thanks! We need to make sure that both Jetpack and MPP Compose are also updated.

**Comment by YektaDev** [comment]
An update: [Compose compiler 1.3.2](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.3.2) is updated to Kotlin 1.7.20

**Comment by arkivanov** [comment]
Yup, now waiting for MPP Component beta03, should be released soon.
