### ISSUE TITLE
C::class.simpleName - possible problem with Proguard

### ISSUE THREAD

**Issue by aartikov** [arkivanov/Decompose#227]
Hi, Arkadii.

As I can see the version 1.0.0-alpha-05 of Decompose uses `simpleName` for default keys of child stack and overlay.
It could cause a problem with Proguard when originally different class names are converted to the same name.
The bug will be catched only on a release (minified) build, that is unpleasant.

What do you think about replacing `C::class.simpleName` with `C::class.qualifiedName`? A `qualifiedName` is guaranteed to be unique.

**Comment by arkivanov** [comment]
Thanks for raising! Unfortunately `qualifiedName` is not available in K/JS. But having the behavior potentially different on different kinds of builds is also not good. I would rather revert the change. Or maybe use `KClass.hashCode` in JS instead of `qualifiedName`. I will think about it and fix soon.

**Comment by arkivanov** [comment]
Or use `KClass.hashCode` instead of `simpleName`, this should disambiguate different classes with the same name.

**Comment by aartikov** [comment]
@arkivanov 
Oh, didn't know that fact about Kotlin/JS.

I feel ok that I need to specify keys explicitly when there are multiple child stacks in a component. It is a quite rare case.
I would prefer safety rather than a little bit of boilerplate code.

What about `KClass.hashCode`, is it guaranteed to be unique? It is quite easy to find two `String`s with the same hash code, for example `"Aa".hashCode() == "BB".hashCode()`. Is it better for `KClass`?

**Comment by arkivanov** [comment]
I think `hashCode` for a class is also not a good idea. It's not guaranteed to be stable, so e.g. after process death on Android, classes may have different hash codes. On JS - it's just `simpleName.hashCode()`.

**Comment by arkivanov** [comment]
Version [1.0.0-alpha-06](https://github.com/arkivanov/Decompose/releases/tag/1.0.0-alpha-06) is released, thanks!
