### ISSUE TITLE
Proper dependency injection (DI)

### ISSUE THREAD

**Issue by Knoxvillekm** [arkivanov/Decompose#238]
How to use it, any sample plz.

**Comment by arkivanov** [comment]
Hello. You can just pass things via constructors, see [example](https://github.com/arkivanov/Decompose/blob/e720a0d2230ca530441bbed72efb97af5d8c06c2/sample/shared/shared/src/commonMain/kotlin/com/arkivanov/sample/shared/counters/CountersComponent.kt#L47).
