### ISSUE TITLE
Missing component lifecycle documentation for different targets

### ISSUE THREAD

**Issue by azlekov** [arkivanov/Decompose#247]
Hey @arkivanov,

I have a common component and in its init I have:

```kotlin
init {
        Logger.d("Init")
        lifecycle.doOnResume {
            Logger.d("onResume")
            reload()
        }

        lifecycle.doOnDestroy {
            if (scope.isActive) {
                scope.cancel()
            }
        }
    }
```

Works like a charm on Android but on iOS I got only `Init` on the log.
I'm using latest alpha 07.

Is there anything special I need to configure on iOS?

**Comment by arkivanov** [comment]
On iOS you have to control the root lifecycle manually. See the example - https://github.com/arkivanov/Decompose/blob/master/sample/app-ios/app-ios/app_iosApp.swift

**Comment by azlekov** [comment]
Thanks! I was missing `onAppear` and `onDisappear`. If is no problem I will open a PR updating the docs 😎

**Comment by arkivanov** [comment]
Sure, it would be good to update the docs! Perhaps in the [lifecycle](https://arkivanov.github.io/Decompose/component/lifecycle/) section? Also worth mentioning [LifecycleController](https://github.com/arkivanov/Decompose/blob/800838e16d43574c19b907829f86e51fc634dcc0/sample/app-desktop/src/jvmMain/kotlin/com/arkivanov/sample/app/Main.kt#L35) for Compose for Desktop and web (not Compose) [root lifecycle control](https://github.com/arkivanov/Decompose/blob/800838e16d43574c19b907829f86e51fc634dcc0/sample/app-js/src/main/kotlin/com/arkivanov/sample/app/Main.kt#L39).

**Comment by arkivanov** [comment]
Thanks for your contribution!
