### ISSUE TITLE
StackRouterView.removeAllViews does not remove all views when triggered twice in a row

### ISSUE THREAD

**Issue by malliaridis** [arkivanov/Decompose#258]
Using the `StackRouterView` and following the examples, the `removeAllViews()` function does not remove the views and loads the layout twice when `replaceChildView` from `children(stack, lifecycle, replaceChildView)` is called multiple times in a row.

### Steps to reproduce

1. In an android project create a component with a childstack and in its layout a `StackRouterView`
2. Add a bottom navigation bar and set an item click listener
3. Bind data so that the menu item from the navigation bar is selected when child stack is updated
4. Set a click listener so that a component function that handles the navigation is triggered on click
5. Run the app and rotate the device
6. Check layout inspector for duplicate layout

When rotating the device `replaceChildView` should be triggered twice in a row, causing the function `removeAllViews` to not clear the views properly.

Reproducible code can be found [here](https://gist.github.com/malliaridis/69c317683ba4790cb05a50570e815680).

### Current Workaround

Due to the limited two-way data binding options my current workaround is to add a configuration check and not navigate when the current active configuration is the same. It would look something like below:
```kotlin
override fun onFirstChildClicked() {
    if (childStack.active.configuration is Configuration.FirstScreen) return
    navigation.replaceAll(Configuration.FirstScreen) // bringToFront behaves the same
}
```

### Further Information

I am not sure if it is a bug or a known behavior. Obviously triggering `onFirstChildClicked` when loading the layout for the first time is not a best practice, but I couldn't find a solution for that to avoid it (other than adding checks in other places).

**I assume the reason why the child layout is loaded twice is because the `StackRouterView` hasn't loaded yet the initial layout from the first call and when calling `removeAllViews()` in the second call it doesn't remove anything, but adds both later.**

_I am aware that the `StackRouterView` is still experimental._

**Comment by arkivanov** [comment]
Thanks for raising! Looking at your code, it appears that you are performing the navigation from inside `srMain.children` lambda. You are setting `binding.bbNavigation.selectedItemId = R.id.first` which in turn triggers the listener and calls `component.onMenuItemClicked`. Instead, you can try observing the router state changes and update the selected item accordingly. Don't forget to remove and re-add the selection listener when changing the selected item. You can refer to the sample [RootView](https://github.com/arkivanov/Decompose/blob/master/sample/shared/shared/src/androidMain/kotlin/com/arkivanov/sample/shared/root/RootView.kt) which covers exactly your use case.

**Comment by malliaridis** [comment]
I see, I was following your sample projects as usual but I probably skipped this part. So the solution would be to not navigate twice by removing and adding the listener and in between update the item. Makes sense.

Thank you very much for the reference. 😄
