### ISSUE TITLE
Broken link to samples in the main readme

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#27]
The "project website" link in the [Samples section](https://github.com/arkivanov/Decompose#samples) of the main README is broken. It should be https://arkivanov.github.io/Decompose/samples/ instead.

**Comment by Aman-Mandal** [comment]
Hey, Can I take this issue?

**Comment by EliavYair1** [comment]
i fixed your issue inside your project please approve :D

**Comment by arkivanov** [comment]
Closed via #28, thanks!

**Comment by EliavYair1** [comment]
you're welcome 👍🏽
