### ISSUE TITLE
```describeContents(): Int``` is not implemented on Android

### ISSUE THREAD

**Issue by DatL4g** [arkivanov/Decompose#273]
I'm working on a multiplatform project (Desktop [JVM] and Android)

Running it on desktop works without any issue, however on Android the build fails with this error:

```
Object 'Login' is not abstract and does not implement abstract base class member public abstract fun describeContents(): Int defined in dev.datlag.burningseries.ui.navigation.NavHostComponent.ScreenConfig
```

You can take a look at the source code at https://github.com/DATL4G/BurningSeries-Android/tree/compose it's in early development, so easy to understand

**Comment by arkivanov** [comment]
Please make sure you have applied the `kotlin-parcelize` plugin - https://github.com/arkivanov/Essenty#parcelable-and-parcelize

I will add this information somewhere in Decompose docs as well.

**Comment by DatL4g** [comment]
I added the plugin for the android sourceSet, however it only builds after adding the ```@Parcelize``` annotation

The build is successful now but the screen is not showing on android

**Comment by DatL4g** [comment]
Works now (with ```@Parcelize```)

On Android we don't create the Nav component blocking in the main thread

**Comment by arkivanov** [comment]
It looks like you have a deadlock in your `runOnMainThreadBlocking` on Android. I think you don't need this, you can just create the root component inside `onCreate` method.

Let's keep the issue open, as I want to update the docs.

**Comment by arkivanov** [comment]
Updated the docs: https://arkivanov.github.io/Decompose/navigation/overview/#configurations-are-parcelable
