### ISSUE TITLE
Rename "router" package to "navigation"

### ISSUE THREAD

**Issue by aartikov** [arkivanov/Decompose#275]
Hi, Arkadii.
My suggestion is to rename "router" package to "navigation".
It is not critical at all, but maybe worth to do before release version.

There is no router concept anymore since `router` was renamed to `childStack`. The word `navigation` fits better, in my opinion. Also it is used overall in the documentation.

**Comment by arkivanov** [comment]
Thanks, I agree. Except for the fact that the library was promoted to Beta recently, which means the API is considered stable. But I will think about it.

**Comment by arkivanov** [comment]
I think it's too late for this change, also `router` package name is not that bad. Will keep this in mind in case of `v2.0` somewhere in the future.
