### ISSUE TITLE
Enable watchos target for the Counter sample after Kotlin 1.5.31 update

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#3]
The Counter sample has `watchos` targets temporary disabled, due to [KT-48613](https://youtrack.jetbrains.com/issue/KT-48613).

**Comment by plusmobileapps** [comment]
Is there anything stopping this work of updating the project to kotlin 1.6.0 to fix the sample? Jetpack compose compiler?

**Comment by arkivanov** [comment]
I think we can update straight to Kotlin 1.6.10 and Compose to v1.0.1-rc2.

**Comment by arkivanov** [comment]
I will do the update in the coming days. There are also some changes in the library, that we can do. E.g. probably we can remove the `-jetpack` module, because the `-jetbrains` can now be used instead. And the latter should be renamed in this case.

**Comment by arkivanov** [comment]
I filed a separate issue for the Kotlin version update: #5
