### ISSUE TITLE
1.0.0-beta-04-native-compose version could not resolved in target iosArm64

### ISSUE THREAD

**Issue by TaehoonLeee** [arkivanov/Decompose#302]
If I bump version to 1.0.0-beta-04-native-compose, an error occurs like below.
`Could not resolve all dependencies for configuration ':common:iosArm64CompileKlibraries'`

It works well in 1.0.0-beta-01-native-compose ~ 1.0.0-beta-03-native-compose

**Comment by arkivanov** [comment]
Thanks for raising! It appears that I published the release from the wrong branch and it didn't went through. I have just re-published it from the correct branch. Should be working now, could you please check?

**Comment by viktor-savchik-idf** [comment]
@arkivanov Hi, I've faced with the similar issue, could you take a look please?
```
:iosArm64Main: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
:iosArm64Test: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
:iosSimulatorArm64Main: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
:iosSimulatorArm64Test: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
:iosX64Main: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
:iosX64Test: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-beta-04
```

**Comment by arkivanov** [comment]
@viktor-savchik-idf It looks like you are trying to use `extensions-compose-jetbrains` for Compose for iOS, you should use `1.0.0-beta-04-native-compose` version. The main release doesn't support Compose for iOS.

**Comment by viktor-savchik-idf** [comment]
@arkivanov with adding native-compose suffix everything works, thanks, sorry for bothering

**Comment by arkivanov** [comment]
Thanks! Closing the issue.
