### ISSUE TITLE
How to write Unit test for Component

### ISSUE THREAD

**Issue by LongJakeparker** [arkivanov/Decompose#306]
Hi Guys,

I want to write the Unit test for my Component class, but there is a ComponentContext as a parameter and I don't know how to create a ComponentContext for testing purposes.

Ex: 
     class Component(viewModelContext: ComponentContext)

In test case:
     val componentContext = ?????
     val component = Component(componentContext)

**Comment by arkivanov** [comment]
You can use `DefaultComponentContext` builder function. You can also use `LifecycleRegistry` to provide the lifecycle and control it manually.

**Comment by arkivanov** [comment]
I will describe it in the documentation.
