### ISSUE TITLE
Maybe always recreate all components in the back stack on configuration change or process death?

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#327]
This is something to think about.

Currently, Decompose only recreates the active component in `ChildStack` on configuration change or process death. Components in the back stack (as well as their retained instances) remain destroyed and are recreated on demand. For example, Android Fragments and ViewModels are always recreated in the back stack. So maybe Decompose should follow the same approach?

This would also simplify the API:

- `ChildStack#backStack` and `ChildStack#items` properties would be of type `List<Child.Created>` instead of `List<Child>`.
- The `backStackCreateDepth` argument of the `ComponentContext.childStack` extension function would be removed as not needed.

**Comment by CoroDesk** [comment]
Yes, please.
But this might result in high memory allocation, what about if we can tell the `childStack` what component should be recreated via each child configuration class? sounds like it would be the right place to define its configuration (😄 ) on whether to keep it destroyed or created.

**Comment by arkivanov** [comment]
Thanks for the reply @CoronelGlober! I already have considered utilising configurations for this. This however would require every configuration to implement an interface. Another idea was to add a special predicate instead of the simple `backStackCreateDepth` parameter - something like `isRecreatable: (C) -> Boolean`. But then I thought, what if a developer needs more complex logic, like recreate a component conditionally taking into account the whole stack. I couldn't find a good and at the same time easy API without specific use cases, and decided to go with `backStackCreateDepth` for now.

Regarding memory allocation - Android already does this for quite some time, so I guess shouldn't be an issue. Taking into account that this is mostly applicable for Android only, I guess we could go the same way? Not 100% sure yet.

Also in case of a special tricky use case (e.g. a stack with a lot of components), one can always use Generic Navigation.

**Comment by JuBan1** [comment]
Hi there,

as I understand it, this would effectively be the same as using `backStackCreateDepth = Int.MAX`? That sounds like a good way to simplify the mental model of the application state at any point in the component stack.

Is there a convenient way to replicate the effect of a configuration change? Preferably in a platform independent way? That would help in experimenting with it and maybe even test covering it.

**Comment by C2H6O** [comment]
The issue with the default setting (`backStackCreateDepth = 0`) is easily reproducible with the following steps:

1. Start with Child A
2. Modify Child A state
3. Navigate to Child B
4. Rotate the device
5. Go back to Child A
6. The state is lost

The state gets retained properly if we rotate the device on Child A.

**Comment by arkivanov** [comment]
@JuBan1 Yes, `backStackCreateDepth = Int.MAX` enables the same behaviour. 

> That sounds like a good way to simplify the mental model

Yes, I agree!

> Is there a convenient way to replicate the effect of a configuration change? Preferably in a platform independent way That would help in experimenting with it and maybe even test covering it.

You can write a test:

1. Create an instance of `StateKeeperDispatcher`.
2. Create an instance of a component, pass that `StateKeeperDispatcher` into `DefaultComponetContext`.
3. Navigate as needed.
4. Save the state using `StateKeeperDispatcher#save` method.
5. Create a new instance of `StateKeeperDispatcher` and pass the saved state.
6. Create a new instance of the component, pass the new instance of `StateKeeperDispatcher` into `DefaultComponentContext`.
7. Verify the stack.

Here is an example of testing state restoration - [CounterComponentTest.kt](https://github.com/arkivanov/Decompose/blob/d708782e889771a5753be59134806d128acdcfe4/sample/shared/shared/src/commonTest/kotlin/com/arkivanov/sample/shared/counters/counter/CounterComponentTest.kt#L82).

**Comment by arkivanov** [comment]
@C2H6O I agree that this change will make it easier to survive configuration changes in the back stack, but there still will be a problem in case of the process death. Most likely you need to preserve (persist) the state anyway via `StateKeeper`. What is more important is that any running background jobs won't be cancelled and restarted.

Btw, you can achieve the same behaviour already by passing `backStackCreateDepth = Int.MAX`.

**Comment by b95505017** [comment]
I found that I didn't set `backStackCreateDepth = Int.MAX` but after configuration changed I still have full active & back stack history. Does it work as expect?

**Comment by arkivanov** [comment]
Without `backStackCreateDepth = Int.MAX`, after configuration change the back stack should contain all the same components, but they should be destroyed (e.g. be `Child.Destroyed`).

**Comment by arkivanov** [comment]
This will be released with next major update.
