### ISSUE TITLE
Testing lifecycle

### ISSUE THREAD

**Issue by Burtan** [arkivanov/Decompose#328]
Hey,

I just realized that the default lifecycle registry `LifecycleRegistry()` does not do anything. I think it should destroy components when they are thrown of the navigation stack. Currently I'm still receiving flows on those components in my tests, even though they are out of the navigation stack.

**Comment by arkivanov** [comment]
Hello. Lifecycle of a component should be destroyed when removed from the stack. Though I'm not sure how `LifecycleRegistry` is related. Could you please provide a reproducer?

**Comment by Burtan** [comment]
Please have a look at this test. I made some editions on your samples for it.
https://github.com/Burtan/Decompose/blob/LifecycleTesting/sample/shared/shared/src/jvmTest/kotlin/NavigationTest.kt

**Comment by arkivanov** [comment]
Thanks! I believe this is by design. Child Stack can't be empty, the type system ensures so. Moreover, it doesn't release references to child instances in the back stack when destroyed. Though, the child lifecycle should be destroyed (e.g. `onDestroy` is called). And since you destroyed the root component, you are safe to release its instance (which is unnecessary in tests).

When a child component is removed from the stack, it's destroyed by the parent and the reference is released automatically.

**Comment by Burtan** [comment]
I'm not sure if I get this correctly. 
I think the behavior of the test should not be desired. Child's that are dismissed from the navigation stack should have a destroyed lifecycle, which does not happen. In contrast, when using the recommended way of implementing the lifecycle registry on android or web, the child's lifecycle is correctly destroyed. That is why I thought, this behavior is related to the lifecycle registry.

**Comment by arkivanov** [comment]
As far as I can see, you are not asserting the child lifecycle. You are asserting the child instance:

```kotlin
assertTrue(customChild is RootComponent.Child.CustomNavigationChild)
```

**Comment by Burtan** [comment]
You might have missed the changes to the repository? I added prints to the counters lifecycle and added a loop in a coroutine running on the lifecycle scope which keeps printing after the counter component was dismissed. I cannot access the lifecycle of the component in the test, that is why I used prints.

https://github.com/arkivanov/Decompose/compare/master...Burtan:Decompose:LifecycleTesting

**Comment by arkivanov** [comment]
Indeed, I didn't notice the changes. I will check that.

**Comment by Burtan** [comment]
Thanks for the fast response and for this great project :-).

**Comment by arkivanov** [comment]
While reading the test code I noticed that you never resume the lifecycle. Perhaps that's why the lifecycle is not `DESTROYED`, as it has to be at least `CREATED` first (as per the [docs](https://github.com/arkivanov/Essenty#lifecycle-state-transitions)). Could you please try adding `lifecycle.resume()` right after component instantiation?

**Comment by arkivanov** [comment]
Perhaps, we could still move the child component to `CREATED` state and then to `DESTROYED` state if it's being removed from the stack without being `CREATED`.

**Comment by Burtan** [comment]
Adding lifecycle.resume() does work for my personal project. In the linked NavigationTest it fails because of some errors in threading where actions from main are required but not done. But that seems unrelated to the lifecycle problem. 
I would propose to add the lifecycle.resume() part to the samples test, like here: 
https://github.com/arkivanov/Decompose/blob/master/sample/shared/shared/src/commonTest/kotlin/com/arkivanov/sample/shared/root/RootComponentIntegrationTest.kt

Code changes on the general behavior of lifecycles could of course be considered as well.

**Comment by arkivanov** [comment]
Sure, I will update the tests, thanks for raising. This however won't affect the tests, since there are no lifecycle assertions on that particular tests.

**Comment by Burtan** [comment]
Yeah, you are right, but people will use them as blueprints ;-), I will close this. 
Thanks for the fast answers again!

**Comment by arkivanov** [comment]
Let's keep this issue open until I update the tests at least.
