### ISSUE TITLE
Un-finished swipe gesture breaks iOS pop navigation

### ISSUE THREAD

**Issue by b95505017** [arkivanov/Decompose#337]
iOS 16 simulator

https://user-images.githubusercontent.com/320815/222780182-276dc2e4-fcea-4f82-9834-0b13ea3c24bf.mp4

**Comment by arkivanov** [comment]
Thanks for the report, I will check that.

**Comment by b95505017** [comment]
This issue also reproducible in my project, basically using the same [`StackView`](https://github.com/arkivanov/Decompose/blob/master/sample/app-ios/app-ios/StackView.swift) (`NavigationStack` in iOS 16) implementation.

**Comment by arkivanov** [comment]
Yeah, seems like there an issue with `StackView`. Not exactly related to Decompose.

cc: @ttypic

**Comment by b95505017** [comment]
`StackView` implementation is the core concept to make Decompose work with SwiftUI navigation, including `NavigationView/NavigationStack` compatibility consideration. Hope there will have a solution soon. 🙏

**Comment by arkivanov** [comment]
I don't think that `StackView` is the core concept. That's just something that we came up with for the Counters sample. You may use it, or create something different. For instance, check out how it was working before the introduction of `StackView` - https://github.com/arkivanov/Decompose/blob/2e41cd3e32e5f44f472acb2f17b4fefe5e07d255/sample/app-ios/app-ios/CountersView.swift

**Comment by b95505017** [comment]
But this way we couldn't use built-in navigation animation and gesture.

**Comment by arkivanov** [comment]
Sure! That's why I will try to fix it. I will appreciate any help here.

**Comment by ttypic** [comment]
@b95505017 thank you for reporting this! I will take a look and try to fix it as soon as possible

**Comment by b95505017** [comment]
By the way, I haven't try OS below iOS 16 (NavigationView or UIKit implementation) yet. It's a different world than NavigationStack, not sure if it has same issue as well.

**Comment by ttypic** [comment]
@b95505017 maybe I am missing something, but I can't reproduce the issue. Could you share Simulator SDK version? Does it always break when you swipe back a little and then release? Are there any special conditions?

**Comment by b95505017** [comment]
@ttypic I use Xcode 14.2 with iPhone 14 pro iOS 16.0 simulator. I'm not sure what happened during swiping so I always swipe over half of the screen and then swipe back.

**Comment by b95505017** [comment]
I test this behavior a bit more, this issue seems only happened on iOS 16.0 simulator, other iOS version (e.g. 15.x, 16.1, 16.2) seems normal. Maybe a `NavigationStack` bug in iOS 16.0?

Then I found [this discussion](https://stackoverflow.com/questions/73978107/incomplete-swipe-back-gesture-causes-navigationpath-mismanagement). From this discussion, we may have to implement `Identifiable` protocol to make it work.

**Comment by ttypic** [comment]
@b95505017 Thank you for further investigation! I can confirm that issue only appears in iOS 16.0 and ensure that it is unfortunately **SwiftUI** bug, we can't do anything with this. 

I tried the solution from SoF, you mentioned, and `Identifiable` protocol makes no difference. I can reproduce the issue with a simple SwiftUI setup without Decompose. If you look at the SoF answer you find that it has zero upvotes and "tested on iOS 16.1".

Btw `NavigationStack` still has some bugs on **SwiftUI** side and you should be careful with it. Look at [this one for instance](https://stackoverflow.com/questions/74598938/search-bar-is-briefly-visible-when-navigating-with-navigationstack-swiftui/). And although the legacy option based on UIKit looks not that elegant it might be a more stable solution.

**Comment by arkivanov** [comment]
Thanks for all the updates! Maybe we could tweak the [available iOS version in StackView](https://github.com/arkivanov/Decompose/blob/de081ddc82396c41685b1e9506700bc61c995e68/sample/app-ios/app-ios/StackView.swift#L18), so `NavigationStack` is only used starting from iOS 16.1?

**Comment by ttypic** [comment]
Couldn't agree more. Created PR with this fix.

**Comment by b95505017** [comment]
BTW I found that there are some issues with UIKit wrapper solution with navigation title and change to [this wrapper](https://github.com/johnpatrickmorgan/NavigationBackport).
