### ISSUE TITLE
Expose stack on StackNavigation

### ISSUE THREAD

**Issue by Burtan** [arkivanov/Decompose#340]
Hi,

currently there seems to be no way to get the stack of StackNavigation? I agree that you don't need it most of the time, but when there is an arbitrary entry point via deep linking, you sometimes have to get the current state of StackNavigation to know if you have to "pop" for going back or if you have to recreate the component that is normally in the backstack.

**Comment by arkivanov** [comment]
Hello. `StackNavigation` doesn't have any state, it's a simple relay forwarding navigation events to `Child Stack`. The latter subscribes to `StackNavigation` and exposes the navigation state. `childStack` function returns `Value<ChildStack>`, where you can read the current navigation state.

**Comment by Burtan** [comment]
Oh cool, thanks :-).
