### ISSUE TITLE
Using extensions-compose-jetbrains on windows will make jvm crash

### ISSUE THREAD

**Issue by elonzh** [arkivanov/Decompose#341]
How to reproduce:

1. Create a compose desktop project
2. Add decompose dependencies
3. Run `gradle run`

```kotlin
kotlin {
    jvm {
        jvmToolchain(11)
        withJava()
    }
    sourceSets {
        val jvmMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                val decomposeVersion = "1.0.0"
                implementation("com.arkivanov.decompose:decompose:$decomposeVersion")
                implementation("com.arkivanov.decompose:extensions-compose-jetbrains:$decomposeVersion")
            }
        }
        val jvmTest by getting
    }
}
```

Logs:

[hs_err_pid9164.log](https://github.com/arkivanov/Decompose/files/10914140/hs_err_pid9164.log)

Dependencies:

![image](https://user-images.githubusercontent.com/8749411/223559206-1bf9b624-9e78-495c-bbd6-89c74765311a.png)

**Comment by elonzh** [comment]
Everything works after upgraded jetbrains compose to "1.3.0"

**Comment by arkivanov** [comment]
Thanks for the update, closing this for now.
