### ISSUE TITLE
FATAL ERROR: Could not find "Essenty:lifecycle" for Experimental Web Canvas

### ISSUE THREAD

**Issue by MohamedRejeb** [arkivanov/Decompose#342]
I was trying to use decompose with the new experimental web canvas but I'm getting this error.

```
> Task :shared:compileKotlinJs FAILED
e: Could not find "Essenty:lifecycle" in [/Users/mohamedbenrejeb/Library/Application Support/kotlin/daemon]
e: java.lang.IllegalStateException: FATAL ERROR: Could not find "Essenty:lifecycle" in [/Users/mohamedbenrejeb/Library/Application Support/kotlin/daemon]
	at org.jetbrains.kotlin.ir.backend.js.KlibKt$resolverLogger$1.fatal(klib.kt:101)
```

**Comment by arkivanov** [comment]
Yeah, I've seen this error as well. I'm not sure what's the cause and how to fix this. AFAIK clean build helped me.

**Comment by arkivanov** [comment]
Is it the sample `shared` model or your own?

**Comment by MohamedRejeb** [comment]
No it's my own, I've seen the sample `shared` module, it's quite different from my owm module. 
I'm not importing Essenty like the sample, I'm just  importing Decompose

Do you think that the problem is related to Essenty library ?

**Comment by arkivanov** [comment]
At the moment, it looks more like a K/JS issue, see similar bug report - [KT-52812](https://youtrack.jetbrains.com/issue/KT-52812). It started happening after update to Kotlin 1.8.0. Could you please try adding `implementation "com.arkivanov.essenty:lifecycle:<essenty_version>"` to your `shared` module's `build.gradle` file?

**Comment by MohamedRejeb** [comment]
Same problem, I think that it's related to the kotlin version, this is a simular issue as well [KT-54406](https://youtrack.jetbrains.com/issue/KT-54406), in this issue the problem was kotlin version but for my case I'm using 1.8.0 and decompose uses the same version as well.

**Comment by arkivanov** [comment]
Is this problem always reproducible for you? Is there any chance you could create a minimal reproducer and either post it here or file a ticket on YouTrack? Asking because for me this issue was flaky. E.g. I had it a couple of times while building Decompose samples locally. But clean build always helped, and I never had this error on CI.

**Comment by MohamedRejeb** [comment]
For me I can't get rid of this problem, even clean build fails for me (gives me some other errors), I will try to make clean build work for me and try again.

**Comment by arkivanov** [comment]
Please also try `./gradlew clean build --no-build-cache --rerun-tasks`.

**Comment by MohamedRejeb** [comment]
I was trying a different solutions but I always get an error from clean build. I'm getting some errors similar to this one below, I think that the problem is in my projects structure, https://github.com/M0Coding/Pokedex this is the project.
If you have any idea how to solve this error help me otherwise I'm going to close this issue because it seams that the problem is not related to decompose or essenty.

`/Users/mohamedbenrejeb/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.0/1796921c7a3e2e2665a83e6c8d33399336cd39bc/kotlin-stdlib-1.8.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

**Comment by arkivanov** [comment]
The last error is a different one. It suggests that that you have a dependency, that is compiled with old version of Kotlin. E.g. this could be Android Gradle Plugin, Detekt, or something else.

**Comment by MohamedRejeb** [comment]
Yes I think that if I could run clean build successfully  I will be able to run the web version, thanks for help Arkadii

**Comment by samandar-me** [comment]
> @MohamedRejeb  Hi bro, I have a same error. Did you solve?

**Comment by rakibishad** [comment]
hii bro same error mine

**Comment by rakibishad** [comment]
how  to solve this problem

**Comment by rakibishad** [comment]
any one helpme

**Comment by arkivanov** [comment]
Please try `./gradlew clean build --no-build-cache --rerun-tasks`. Also please try closing the project, deleting the `.idea` folder, and reopening the project again. Another thing to try - invalidate caches and restart the IDE. Also worth trying deleting the global and the project Gradle cache folders.

If nothing helps, please file a bug at https://youtrack.jetbrains.com/newIssue?draftId=25-4937642.
