### ISSUE TITLE
Decompose Errors when a new AWT-EventThread-0 is spun up after the last one is shutdown

### ISSUE THREAD

**Issue by Syer10** [arkivanov/Decompose#343]
On MacOS when someone closes the application we leave it running in the background so that they can click the toolbar and open it again. This behavior on MacOS will cause the AWT-EventQueue-0 to shutdown between application restarts, and it will have a new Thread ID when the window is opened again.

This leads to Decompose erroring when we update a MutableValue, since it still has the old main Thread ID stored as a global variable.

Example application: https://github.com/Syer10/Decompose-Issue

**Comment by arkivanov** [comment]
Thanks for raising! I will confirm with the Compose team wither this behaviour is by design or a bug.

**Comment by arkivanov** [comment]
`MutableValue` will be thread-safe in the next major release. Navigation from a background thread won't crash, but will likely report an error.
