### ISSUE TITLE
Incompatible with kotlin 1.8.20

### ISSUE THREAD

**Issue by b95505017** [arkivanov/Decompose#368]
[MyApplication2.zip](https://github.com/arkivanov/Decompose/files/11218080/MyApplication2.zip)

![截圖 2023-04-08 上午10 35 52](https://user-images.githubusercontent.com/320815/231651264-296f2423-ff29-4b74-8c6f-129c07d4df91.png)

Either export library or expose library class will throw this error.

**Comment by arkivanov** [comment]
Thanks for raising! It appears that you are compiling Decompose itself. Why do you need this? Normally you should you use the published artifacts, see the [docs](https://arkivanov.github.io/Decompose/getting-started/installation/).

Decompose needs to be updated to Kotlin 1.8.20, but there are bunch of transitive dependencies that have to be updated first.

**Comment by b95505017** [comment]
@arkivanov Nope I just follow docs to import published artifacts. You could check my sample project.

**Comment by arkivanov** [comment]
The attached sample project successfully builds via `./gradlew build`. Are there any steps to reproduce? The error on the screenshot clearly mentions Decompose source code being compiled, which shouldn't happen if you use published artifacts.

![image](https://user-images.githubusercontent.com/26204457/231703461-86445005-8221-4d66-b4c5-dd19a033e57a.png)

**Comment by b95505017** [comment]
@arkivanov Sorry I forget to mention that you should run as iOS. The screenshot is from Xcode.

**Comment by arkivanov** [comment]
Thanks, reproduced. I will update Decompose in the coming days.

**Comment by b95505017** [comment]
Just wondering the root cause.

**Comment by arkivanov** [comment]
Me too! I'm investigating this.

**Comment by xxfast** [comment]
Reproducer here https://github.com/xxfast/NYTimes-KMP/pull/6

**Comment by arkivanov** [comment]
It looks like the error message is a bit misleading. It says "File being compiled", however this happens during the linking stage. There is a bug in the `parcelize-darwin` plugin: some of the generated companion objects are missing primary constructors, and it looks like the new Kotlin `1.8.20` is stricter and now throws an error when linking those objects.

Please expect an updated release in the coming days.

**Comment by arkivanov** [comment]
Version [2.0.0-alpha-02](https://github.com/arkivanov/Decompose/releases/tag/2.0.0-alpha-02) is released, this issue should be fixed now.

**Comment by b95505017** [comment]
@arkivanov Thank you 👍

**Comment by xxfast** [comment]
[Working](https://github.com/xxfast/NYTimes-KMP/pull/6) as intended 👍 Thank you
