### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by VladislavSumin** [arkivanov/Decompose#375]
decompose version [2.0.0-compose-experimental-alpha-02](https://github.com/arkivanov/Decompose/releases/tag/2.0.0-compose-experimental-alpha-02) declare wasm support, but have no sources for wasm on mavenCentral repository.

does decompose support wasm?

compose now support wasm experimental target:
https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-imageviewer#compose-multiplatform-for-web

**Comment by arkivanov** [comment]
It declares Compose for Web (Canvas) support, which is the usual Kotlin/JS target. See the sample - https://github.com/arkivanov/Decompose/blob/compose-experimental/sample/app-js-compose/src/jsMain/kotlin/com/arkivanov/decompose/sample/app/Main.kt#L29

**Comment by VladislavSumin** [comment]
Yes, this is my mistake, now I see support for Web/Js (Canvas), but what about wasm? have any plans to experimental support it?

**Comment by arkivanov** [comment]
Yeah, I could try. Let's keep this issue open.

**Comment by arkivanov** [comment]
It appears that `wasm` target and Compose for wasm are very experimental. E.g. the IDE support is limited, there are no stable coroutines for that target (there is separate experimental repository), Compose for wasm is also published into separate experimental repository, tests are not running for some reason, etc.

Let's wait until this thing matures a bit.

**Comment by arkivanov** [comment]
Let's track this in the existing issue: #74.
