### ISSUE TITLE
Missing native artifacts for 2.0.0-alpha-02

### ISSUE THREAD

**Issue by minaEweida** [arkivanov/Decompose#382]
Hi I was trying to add `2.0.0-alpha-02` and it failed to find dependency for iOS targets.

Looking into maven for any iOS target (check [here](https://repo1.maven.org/maven2/com/arkivanov/decompose/extensions-compose-jetbrains-iossimulatorarm64/)), I see that last release was `2.0.0-compose-experimental-alpha-02` which I was able to resolve.

I can see `2.0.0-alpha-02` published correctly for [Android](https://repo1.maven.org/maven2/com/arkivanov/decompose/decompose-android/2.0.0-alpha-02/) and [jvm](https://repo1.maven.org/maven2/com/arkivanov/decompose/extensions-compose-jetbrains-jvm/2.0.0-alpha-02/). Maybe I am mistaken but could this be a problem with publishing artifacts to native targets, because I see also missing for Mac OS

**Comment by arkivanov** [comment]
The `extensions-compose-jetbrains` module only supports native (and Web) targets on the `compose-experimental` branch. On the main branch, only the core `decompose` module supports native targets.

**Comment by minaEweida** [comment]
Sorry I must have missed that, thought because alpha is after the experimental that it will also include the native targets 😁 .

**Comment by arkivanov** [comment]
Yeah, I'm considering moving the support of the native Compose to the main branch. Thanks for raising!
