### ISSUE TITLE
`Lifecycle.state` returns incorrect values

### ISSUE THREAD

**Issue by 05nelsonm** [arkivanov/Decompose#385]
Not sure if this is a bug, or what is going on here. Am new to Decompose but just wanted to ask.

Currently running on JVM (desktop) using jetbrains compose.

```kotlin
import com.arkivanov.essenty.lifecycle.subscribe

interface HomeComponent {
    fun onClick()
}

class DefaultHomeComponent(
    val context: ComponentContext,
    val onNextScreen: () -> Unit,
): HomeComponent {

    override fun onClick() { onNextScreen() }

    init {
        context.lifecycle.subscribe(
            onCreate = {
                println("${this::class.simpleName} onCreate[state=${context.lifecycle.state}]")
            },
            onStart = {
                println("${this::class.simpleName} onStart[state=${context.lifecycle.state}]")
            },
            onResume = {
                println("${this::class.simpleName} onResume[state=${context.lifecycle.state}]")
            },
            onPause = {
                println("${this::class.simpleName} onPause[state=${context.lifecycle.state}]")
            },
            onStop = {
                println("${this::class.simpleName} onStop[state=${context.lifecycle.state}]")
            },
            onDestroy = {
                println("${this::class.simpleName} onDestroy[state=${context.lifecycle.state}]")
            },
        )
    }
}
```

Navigating to the next screen (i.e. `navigation.push(Config.NextScreen)` from the `RootComponent`) results in the following output.

```
DefaultHomeComponent onCreate[state=CREATED]
DefaultHomeComponent onStart[state=STARTED]
DefaultHomeComponent onResume[state=RESUMED]
// onClick invoked here
DefaultHomeComponent onPause[state=STARTED]
DefaultHomeComponent onStop[state=CREATED]
```

The callbacks are being invoked in the correct order, but reading `context.lifecycle.state` when they **are** invoked shows a different state value (`onPause` and `onStop`).

**Comment by arkivanov** [comment]
Thanks for asking! What would be a correct output from your point of view?

**Comment by 05nelsonm** [comment]
Ideally `onPause` would show `PAUSED`, and `onStop` would show `STOPPED`, but seeing now that `Lifecycle.State` does not include those.

**Comment by arkivanov** [comment]
Yes, the lifecycle is switching between RESUMED, STARTED, and CREATED states, and in the end goes to to DESTROYED state. See the doc - https://arkivanov.github.io/Decompose/component/lifecycle/

**Comment by 05nelsonm** [comment]
For sure for sure. I apologize, as I should have looked into docs more before submitting an issue and unnecessarily consuming your time. Will close, Thanks!
