### ISSUE TITLE
There is not a @Composable function  for ChildSlot like Children?

### ISSUE THREAD

**Issue by notbetop** [arkivanov/Decompose#395]

**Comment by arkivanov** [comment]
No, there is not. The `Children` function preserves the UI state for the components in the stack, and also animates transitions between them. This is not required for the simple case with one single child component, aka `ChildSlot`. The state should be preserved by Compose automatically (or can be easily done manually). Transitions are either provided by Compose components (like `Dialog`, `ModalBottomSheet`, etc.), or you can use Compose animations like `AnimatedVisibility`).

**Comment by notbetop** [comment]
I didn't understand it thoroughly. I will close the question.
