### ISSUE TITLE
Predictive back gesture doesn't restore the UI state of the previous screen

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#403]
Likely, there will be breaking API changes.

**Comment by alexzhirkevich** [comment]
Probably can be workarounded using `rememberSaveable` with `key` if they share SavedStateHandle. Not tested, but had the same issue when implementing swipe back gesture

**Comment by arkivanov** [comment]
The UI state is being preserved in the `Children` function [here](https://github.com/arkivanov/Decompose/blob/327000d7c8289bf238d4947e61aafd08eeb0ff5c/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/Children.kt#L30). The provided `animation` calls its `content` slot for each child screen, and the state is saved/restored accordingly. This works just fine when screens are switched programmatically.

Currently, there is [PredictiveBackAnimation](https://github.com/arkivanov/Decompose/blob/v2.1/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/PredictiveBackAnimation.kt) which is an animation wrapper. It wraps another animation (used for programmatic navigation), and basically calls that animation with different stacks, one for the current screen and another one for the previous screen.

In order for that to work, [different keys are required](https://github.com/arkivanov/Decompose/blob/v2.1/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/PredictiveBackAnimation.kt#L88) for each screen. And this prevents the state from being restored, because the sub-tree composition key becomes different.

This probably could be solved without breaking the API by using `movableContentOf`. But this feature has proven to be buggy, so I would like to avoid it as much as I can.

Another solution would be to supply an optional `PredictiveBackGestureConfig` to the main animation, e.g. [here](https://github.com/arkivanov/Decompose/blob/327000d7c8289bf238d4947e61aafd08eeb0ff5c/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/StackAnimation.kt#L57). This would delegate the responsibility to the main animation, so it could handle all cases correctly. This option is not as good as the current approach in terms of the API surface. But it should be more reliable, and should solve this bug.
