### ISSUE TITLE
Version 2.1.0-compose-experimental-alpha-03 isn't published yet

### ISSUE THREAD

**Issue by Tiebe** [arkivanov/Decompose#421]
The alpha-03 version for extensions-compose-jetbrains isn't published yet, see here: https://central.sonatype.com/artifact/com.arkivanov.decompose/extensions-compose-jetbrains/2.1.0-compose-experimental-alpha-02/versions

**Comment by arkivanov** [comment]
Thanks for noticing! It appears that I forgot to bump the version and the release didn't go through. Publishing now: https://github.com/arkivanov/Decompose/actions/runs/5436308217

**Comment by arkivanov** [comment]
Published. Artifacts should become available without ~1hour.
