### ISSUE TITLE
2.1.0-compose-experimental-alpha-05 breaks predictive back on Android 

### ISSUE THREAD

**Issue by xxfast** [arkivanov/Decompose#426]
2.1.0-compose-experimental-alpha-03

https://github.com/arkivanov/Decompose/assets/13775137/d30225ed-8e3f-4e3f-96ca-19ccf313420c

2.1.0-compose-experimental-alpha-05

https://github.com/arkivanov/Decompose/assets/13775137/c9ecb911-d779-4117-816e-3539fdc52445

Reproducer: https://github.com/xxfast/NYTimes-KMP/pull/50

**Comment by arkivanov** [comment]
The newer version depends on `androidx.activity` version `1.8.0-alpha06`, which requires Android API 34 (not `UpsideDownCake`) in order for predictive back gesture to work. Please update your Android SDK and use an emulator with API 34. Please check `Build.VERSION.SDK_INT` at runtime, it should return 34. On `UpsideDownCake` emulators it returns 33.

**Comment by xxfast** [comment]
Yup that worked 👍 Needed to download the latest SDK 34 via the device manager 

https://github.com/arkivanov/Decompose/assets/13775137/585eea6f-6b55-439b-a162-13e35bf0e51b

**Comment by arkivanov** [comment]
Awesome!
