### ISSUE TITLE
Pages Composable takes up entire width

### ISSUE THREAD

**Issue by DatL4g** [arkivanov/Decompose#427]
The new `Pages` Composable takes up the entire width (maybe even whole size).

Example:

```kotlin
Box(
	modifier = Modifier.background(Color.Red),
	contentAlignment = Alignment.TopStart
) {
	Pages(
		pages = component.pages,
		onPageSelected = { index ->
			component.selectPage(index)
		},
		modifier = Modifier.background(Color.Green)
	) { index, page ->
		page.render()
	}
}
```

Rendered Page:

```kotlin
Column(modifier = Modifier.background(Color.Blue)) {
	// render another child here
}
```

Result:

![Bildschirmfoto vom 2023-07-07 15-15-11](https://github.com/arkivanov/Decompose/assets/46448715/c139531e-6195-479c-81f8-53c78444ab0b)

As you can see the Box background (RED) isn't visible and the Pages background (GREEN) takes up the entire width, even though the renderd page (BLUE) is way smaller.

## Reproducing

Checkout this project https://github.com/DATL4G/eSports-Prodigy

The `app/src/commonMain/kotlin/dev/datlag/esports/prodigy/ui/screen/home/HomeScreen` contains a ExpandedScreen composable with the Box and Pages, just add the background Modifier as described in the example.

The `app/src/commonMain/kotlin/dev/datlag/esports/prodigy/ui/screen/home/info/InfoView` contains the Column, just add the background Modifier as described in the example.

**Comment by arkivanov** [comment]
Thanks for reporting! Pages delegates to HorizontalPager under the hood, so I recommend reporting this issue in https://github.com/JetBrains/compose-multiplatform.

Also this might be the same issue as the one I reported a while ago: https://github.com/JetBrains/compose-multiplatform/issues/3272.

**Comment by arkivanov** [comment]
Closing this for now.
