### ISSUE TITLE
Annotate `stackAnimation {}` with an annotation meaning that it uses buggy Compose API

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#429]
`stackAnimation {}` uses `movableContentOf` which is known to contain bugs. This can't be avoided without changing the Decompose API, however in the long term it should become stable.

**Comment by YektaDev** [comment]
Reminds me of the weird exceptions I was faced with in the past; all because I provided a `stackAnimation` in `Child`. It actually took me a while to figure it out.

**Comment by arkivanov** [comment]
Yeah. Please note that only `stackAnimation` function overload is affected. Specifically: 

`stackAnimation { child, otherChild, direction -> ... }`.
