### ISSUE TITLE
Child is not created on forward press. Composable does not render.

### ISSUE THREAD

**Issue by amuna** [arkivanov/Decompose#43]
This is the flow when website is launched.

1. Starts on Homepage. 
2. Click on Button to show next screen. (router.push(Config.Splash) )
3. user press back button (returns to homepage) 
4. user pressed forward button 
5. Blank white screen is seen. How to create child when forward is pressed?

```
private val router: Router<Config, Any> =
        router(
            initialStack = { getInitialStack(deepLink) },
            handleBackButton = true,
            childFactory = ::createChild
        )

private fun createChild(config: Config, componentContext: ComponentContext): Any =
        when (config) {
            is Config.Splash -> Nav.Child.Splash()
            is Config.HomePage -> Nav.Child.HomePage()
            else -> {}
        }

```

**Comment by arkivanov** [comment]
Hello @amuna. You can check the [Counter](https://github.com/arkivanov/Decompose/tree/master/sample/counter) sample, it should work fine with this scenario. Here is the [Root component](https://github.com/arkivanov/Decompose/blob/master/sample/counter/shared/src/commonMain/kotlin/com/arkivanov/sample/counter/shared/root/CounterRootComponent.kt). Also please make sure you [configured your app properly](https://arkivanov.github.io/Decompose/router/browser-history/#configuring-the-application).

https://user-images.githubusercontent.com/26204457/155152943-47eb287c-bb1b-4a98-a5b6-a609835b10da.mp4

**Comment by amuna** [comment]
Hi @arkivanov. The app is configured properly and is in the correct directory. I'm following the ToDo app structure and it appears to be different than the counter app. What I've noticed is that the Config will be pushed by the router when browser back pressed but the screens wont render via crossfade. I've added some more code which may help. Thank you for your time.

```
interface Nav {
    val routerState: Value<RouterState<*, Any>>

    sealed class Child {
        class Splash
        class HomePage
    }
}


@OptIn(ExperimentalDecomposeApi::class)
class NavComponent(
    componentContext: ComponentContext,
    urlExt: String? = null,
    deepLink: DeepLink = DeepLink.None,
    webHistoryController: WebHistoryController? = null,
): Nav, ComponentContext by componentContext {

    private val router: Router<Config, Any> =
        router(
            initialStack = { getInitialStack(deepLink) },
            handleBackButton = true,
            childFactory = ::createChild
        )


private fun createChild(config: Config, componentContext: ComponentContext): Any =
        when (config) {
            is Config.Splash -> Nav.Child.Splash()
            is Config.HomePage -> Nav.Child.HomePage()
            else -> {}
        }

fun pushHomepage() {
        router.push(Config.HomePage())
    }

open class Config(var route: String) : Parcelable{
        @Parcelize
        object Splash : Config("Welcome")

        @Parcelize
        class HomePage : Config("SignUp")
}

//In TodoRootUi.kt This does not get triggered when back button is pressed.
@Composable
fun TodoRootUi(component: NavComponent) {
        val routerState by component.routerState.subscribeAsState()

        Crossfade(
            target = routerState.activeChild.instance,
            attrs = {
                style {
                    width(100.percent)
                    height(100.percent)
                    position(Position.Relative)
                    left(0.px)
                    top(0.px)
                }
            }
        ) { child ->
            when (child) {
                is Nav.Child.Splash -> Splash(component)
                is Nav.Child.HomePage -> HomePage(component)
            }
        }
    }

**Comment by arkivanov** [comment]
> What I've noticed is that the Config will be pushed by the router when browser back pressed

Perhaps, you meant "when browser forward pressed", not "back"? Because as per the initial comment: "Blank white screen is seen. How to create child when forward is pressed?".

> I'm following the ToDo app structure and it appears to be different than the counter app.

The [Todo sample app](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp) does not support web history routing. If you are trying to add the web history routing to the Todo sample app, then there are at least two possible issues:

1. The web app uses an in-memory storage. If for some reason the app is reloaded, then the todo item you are trying to go to might be missing in the storage.
2. There might be an issue with `Crossfade`. I added this animation just for fun, it might have bugs.

I can try the web routing with the todo sample app a bit later.

**Comment by amuna** [comment]
Yes, I meant forward press.

**routerState.activeChild.instance** in crossfade parameter is returning a unit when forward is pressed rather than Child. That is why a blank white screen is being shown. Web routing on todo app would be great! I had an idea of keeping my own stack which tracks the progress of the router stack. And whenever a Unit is received in the crossfade, we would know forward is pressed. I can then load up the correct screen. Not the cleanest way but it could work for now.

```
Crossfade(
            target = routerState.activeChild.instance, //returns Unit on forward press
            attrs = {
                style {
                    width(100.percent)
                    height(100.percent)
                    position(Position.Relative)
                    left(0.px)
                    top(0.px)
                }
            }

**Comment by arkivanov** [comment]
> routerState.activeChild.instance in crossfade parameter is returning a unit

This sounds like a bug, most likely in the JS compiler. Because `routerState.activeChild.instance` should return a `Child`, as per its type. I will check and provide updates here. Thanks for raising!

> Web routing on todo app would be great

The main issue with it in the todo app is the in-memory database. Deep-links will not work properly. E.g. if you open the details screen of an item and click the Browser's refresh button, the app will be reloaded and there will be no item to display.

**Comment by arkivanov** [comment]
@amuna I tried to add the web history to the sample todoapp, everything works as expected. I uploaded the changes to the [todoapp-web-history](https://github.com/arkivanov/compose-jb/tree/todoapp-web-history) in my fork, here is the commit: [829e9d1a23f9046d9ea09cb16d5f78d341092231](https://github.com/arkivanov/compose-jb/commit/829e9d1a23f9046d9ea09cb16d5f78d341092231).

https://user-images.githubusercontent.com/26204457/155584302-a87fa506-9fdd-463a-9e1f-afd61d8067dc.mp4

**Comment by arkivanov** [comment]
Closing the issue for now. Feel free to reopen if there are any questions or concerns.

**Comment by amuna** [comment]
> 1. The web app uses an in-memory storage. If for some reason the app is reloaded, then the todo item you are trying to go to might be missing in the storage.

Yes I've observed this issue when refresh is pressed, that app is restarted from the beginning. Is there a way to prevent this? One idea I had was store the current state of the app in cache and if a restart occurs and cache is not empty, then we can reload the app with the saved information. Do you have another approach to handle this situation.

**Comment by arkivanov** [comment]
@amuna I'm not quite experienced in Web dev. Perhaps the database instance can be retained via `window.sessionStorage`. See https://stackoverflow.com/questions/16206322/how-to-get-js-variable-to-retain-value-after-page-refresh

If this works, you may also want to retain the root `StateKeeper` and `InstanceKeeper`, so the navigation state and objects like Stores are also retained. Not sure how good is this idea, though. Will play with it later.

**Comment by arkivanov** [comment]
Turned out that `sessionStorate` can only store strings. Serializing a database into a string is probably a terrible idea.

There is [absurd-sql](https://github.com/jlongster/absurd-sql), which looks like a persistent storage for browsers. I [mentioned](https://github.com/cashapp/sqldelight/issues/2694#issuecomment-1035589713) it in a SQLdelight 2.0 thread that it would be good to support, but got no response so far. Wondering if absurd-sql can still be used in Kotlin/JS.
