### ISSUE TITLE
Lifecycle-aware navigation

### ISSUE THREAD

**Issue by paxbun** [arkivanov/Decompose#431]
I'm making an app using Decompose + Compose Multiplatform. I've used NavHost from Android Compose, and I'm rewriting that part with Decompose.

I noticed that the rewritten version can push multiple configurations erroneously when two buttons are tapped simultaneously, or tapping a button repetitively in a short time. Consider the following example:

```kotlin
interface MainComponent {
  fun openFoo()
  fun openBar()
}

class DefaultMainComponent(
  componentContext: ComponentContext,
  private val navigation: StackNavigation<Config>, // Injected by RootComponent
) : RootComponent, ComponentContext by componentContext {
  override fun openFoo() {
    navigation.push(Config.Foo)
  }
  override fun openBar() {
    navigation.push(Config.Bar)
  }
}

@Composable
fun MainComponent.View() {
  Button(::openFoo) { Text("Open Foo") }
  Button(::openBar) { Text("Open Bar") }
}
```

When both buttons are tapped simultaneously, both `Foo` and `Bar` is pushed into the navigation stack. This is different from the behavior of `NavHost`, since it cancels the slower `navController.navigate` call so only one path is pushed.

As a workaround, I'm wrapping all calls of `navigation.push` with `if (lifecycle.state == Lifecycle.State.RESUMED)` like the following:
```kotlin
class DefaultMainComponent(...) : ..., ComponentContext by ... {
  override fun openFoo() {
    // lifecycle is in ComponentContext
    if (lifecycle.state == Lifecycle.State.RESUMED) {
      navigation.push(Config.Foo)
    }
  }
  override fun openBar() {
    if (lifecycle.state == Lifecycle.State.RESUMED) {
      navigation.push(Config.Bar)
    }
  }
}
```
This will prevent both configurations are pushed because in this case `navigation.push` is not called recursively so it runs all the lifecycle-related required logic (through the observer set by the `ChildStack`) before returning.

Maybe I'm not using the classes as intended, but shouldn't `StackNavigation` hold a `LifecycleOwner` so it prevents users from wrongly pushing multiple configurations at once? I think adding a class like `LifecycleStackNavigator` and making it created in `ComponentContext.childStack` would be great.
```kotlin
class LifecycleStackNavigator<C : Any>(
  lifecycleOwner: LifecycleOwner,
  private val navigator: StackNavigator<C>,
) : StackNavigator<C> {
  private val lifecycle = lifecycleOwner.lifecycle
  private inline fun runIfActive(block: () -> Unit) {
    if (lifecycle.state == Lifecycle.State.RESUMED) { block() }
  } 
  override fun navigate(
      transformer: (stack: List<C>) -> List<C>,
      onComplete: (newStack: List<C>, oldStack: List<C>) -> Unit,
  ) = runIfActive { navigator.navigate(transformer, onComplete) }
}

inline fun <reified C : Parcelable, T : Any> ComponentContext.childStack(
  source: StackNavigation<C>,
  ...,
  noinline childFactory: (C, ComponentContext, LifecycleStackNavigator<C>) -> T
); Value<ChildStack<C, T>> = childStack(
  source = source,
  ...,
  childFactory = { config, componentContext -> 
    childFactory(
      config,
      componentContext,
      LifecycleStackNavigator(componentContext, source),
    )
  },
)
```

**Comment by arkivanov** [comment]
> shouldn't StackNavigation hold a LifecycleOwner so it prevents users from wrongly pushing multiple configurations at once

This wouldn't work. In your case, the navigation is performed on the root level by events from the child Main component. The root component's lifecycle is not affected by the navigation, and so wouldn't prevent pushing multiple components.

Currently, the `Children` function [displays](https://github.com/arkivanov/Decompose/blob/0f3b440807a73572f19cd4ef0ba3f3cf512a886f/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/AbstractStackAnimation.kt#L56) a transparent overlay on top of all children and intercepts all input events during transition animations. This happens immediately in the first composition with the second child screen pushed (when the animation begins). But it looks like Compose is not fast enough and some events may still pass through, if you click really fast.

I will whether this is a Compose bug, or if I could improve this on the Decompose side.

**Comment by arkivanov** [comment]
I tried the sample app on Android and Desktop (Linux) and couldn't reproduce the issue. Could you please provide more information? What platform you are using? Compose and Kotlin versions? Maybe you could provide a reproducer?

**Comment by paxbun** [comment]
I'm using Compose 1.4.1 with Kotlin 1.8.20 on Android and iOS. Here's an example you can check: https://github.com/paxbun/compose-multiplatform-ios-android-template/tree/decompose-bug-reproduction
This example is created using the official iOS template, so please check the latest commit to see the changes I made.

I haven't included animation in that example, but with navigation animation, this is almost 100% reproducible in every simultaneous multiple-button touch.

Here's the result:

https://github.com/arkivanov/Decompose/assets/17005454/6ab3c24d-1ead-44f7-a0f2-b8b2774afb13

https://github.com/arkivanov/Decompose/assets/17005454/11ec507e-fcec-49f2-9aee-d8b5c1e3a8da

**Comment by paxbun** [comment]
In the case of tapping one button repetitively in a short time, it was `Dialog` that caused the problem, i.e.:
```kotlin
Dialog(...) {
  Surface(...) {
    Button(::openFoo) { ... }
    Button(::openBar) { ... }
  }
}
```

Since the content of `Dialog` is rendered in a separate Android dialog (i.e., outside of the current Compose hierarchy AFAIK) and the dialog is dismissed slightly slower when disposed of, you can still click the buttons in the dialog after the navigation and before the dialog is completely disappeared.

This problem gets more severe when I do the same thing (draw content on a separate `ComposeUIViewController`) on iOS with modal sheets:
```kotlin
@Composable
fun ModalSheet(
  ...,
  content: @Composable () -> Unit
) {
  val modalController = remember {
    ComposeUIViewController {
      MyTheme {
        Surface(...) { content() }
      }
    }.apply {
      sheetPresentationController?.also {
        it.preferredCornerRadius = 20.0
      }
    }
  }
  val currentUIViewController = LocalUIViewController.current
  DisposableEffect(..., visible) {
    if (visible) {
      currentUIViewController.presentViewController(
          modalController, animated = true, completion = null
      )
      onDispose {
          modalController.dismissViewControllerAnimated(flag = true) {}
      }
    } else {
      onDispose {}
    }
  }
}
```

On iOS, even after `dismissViewControllerAnimated(flag:completion:)` is called, the user can hold the sheet and pull it up or pull it down. The modal sheet does not disappear from the screen until the user releases it. While being held, the content in the modal sheet is interactive, and the user can still click the buttons in the sheet, which enables the user to call the navigation function even after the Decompose component is paused or destroyed (although this is an invalid access to a Component in terms of lifetime, there would be people who want to use component functions inside a dialog).

**Comment by arkivanov** [comment]
Thanks for the updates!

>  this is almost 100% reproducible in every simultaneous multiple-button touch

I would say this is expected behaviour. In your sample, each button pushes different screen. The user may push two buttons while the main screen is resumed, and then each event is processed separately and pushes a child screen. The `Children` can't prevent this.

If you really want to prevent this, you could try adding the following functions to your project.

```kotlin
inline fun Lifecycle.doIfResumed(block: () -> Unit) {
    if (state == Lifecycle.State.RESUMED) {
        block()
    }
}

inline fun LifecycleOwner.doIfResumed(block: () -> Unit) {
    lifecycle.doIfResumed(block)
}
```

Then in your `MainComponent` you can do the following. This should solve the issue.

```kotlin
    override fun openFoo() {
        doIfResumed { navigator.push(Config.Foo) }
    }
```

> In the case of tapping one button repetitively in a short time, it was Dialog that caused the problem

So first of all, I couldn't reproduce the issue with dialog on Android. Once a button in the dialog is clicked first time, the navigation state changes synchronously on the same call stack (from click listener), the dialog begins to dismiss. The second click doesn't work, at least I couldn't reproduce. It is important to perform the navigation from the click listener, without any async work.

But anyway, the same solution above should help here as well.

Overall, currently I don't see any ways to improve the experience on the Decompose side. Let me know if you have any ideas!

**Comment by paxbun** [comment]
Thanks for your detailed answer! I decided to use the `LifecycleStackNavigator` I mentioned in the first comment. I believe that there would be many people who may have the same difficulties when using Decompose, so I'm leaving some code I'm actually using here.

I'm using Decompose with Koin, and `StackNavigator` is injected using Koin as well in my project.
```kotlin
// In the module definition
val navigation = StackNavigation<Config>()
val koinModule = module {
  single<StackNavigator<Config>> { navigation }
}

// In components
val navigation: StackNavigator<Config> by inject()
```

I changed these like the following.
```kotlin
// In the module definition
val navigation = StackNavigation<Config>()
val koinModule = module {
  factory<StackNavigator<Config>> { LifecycleNavigator(it[0], navigation) }
}

// In components
val navigation: StackNavigator<Config> by inject { parametersOf(this) }
```

Thanks @arkivanov again for sparing your time and effort on this!

**Comment by arkivanov** [comment]
Thanks for sharing!

Just keep in mind that you are coupling all your components with the same Config class, e.g. every child component is aware of the configuration class used for navigation in the root. This may work in a small project, but at scale this is a big limitation that reduces component reusability.

The recommend practice is to pass callbacks to child constructors and let the parent decide what to do. The parent may either handle the event, or bubble it further to the upper level.

This also allows placing child components in separate Gradle modules, without any dependency on a "core" module with shared navigation things (like screen configurations).
