### ISSUE TITLE
Where to find 2.0.x document and sample code?

### ISSUE THREAD

**Issue by phasedarray** [arkivanov/Decompose#440]
All 2.0.x documents and sample codes are about 1.0.x。Where to get these things about 2.0.x?

**Comment by arkivanov** [comment]
All docs should be already up to date. Do you see any issues?

**Comment by phasedarray** [comment]
The navigator example is based on 'com.arkivanov.decompose:decompose:1.0.0-beta-01'. Here's the link: https://github.com/arkivanov/ComposeNavigatorExample
So where's the example based on 2.0.1?

**Comment by arkivanov** [comment]
Oh, that repository is not even part of the documentation.  I think that is for one of the articles I wrote some time ago.

The official sample is here: https://github.com/arkivanov/Decompose/tree/master/sample
Here is the same sample but with Compose for iOS: https://github.com/arkivanov/Decompose/tree/compose-experimental/sample

**Comment by phasedarray** [comment]
> Oh, that repository is not even part of the documentation. I think that is for one of the articles I wrote some time ago.
Yes, the articles is quoted in "Articles" part of README.md. 
Thank you for instruction. Actually i'm looking for a navigation solution for both desktop and mobile. Any sample code can cover these cases?

**Comment by phasedarray** [comment]
> Oh, that repository is not even part of the documentation. I think that is for one of the articles I wrote some time ago.
> 
> The official sample is here: https://github.com/arkivanov/Decompose/tree/master/sample Here is the same sample but with Compose for iOS: https://github.com/arkivanov/Decompose/tree/compose-experimental/sample

Yes, the articles is quoted in "Articles" part of README.md.
Thank you for instruction. Actually i'm looking for a navigation solution for both desktop and mobile. Any sample code can cover these cases?

**Comment by arkivanov** [comment]
The samples I provided above have a desktop app, as well as Android and iOS apps. The navigation is shared. You can also check the "used by" list: https://github.com/arkivanov/Decompose/discussions/366

**Comment by phasedarray** [comment]
thank you for help!
