### ISSUE TITLE
How to manually destroy component created with `retainedComponent`?

### ISSUE THREAD

**Issue by PhilipDukhov** [arkivanov/Decompose#445]
I have an existing application that uses Jetpack Navigation. I want to migrate it to Decompose, but I want to do it slowly.

So I started with one set of screens. I create a component in one of the Jetpack Navigation destinations.

I get my Activity from the `LocalContext`. First I tried creating the component using `activity.defaultComponentContext()` - it works fine, but when I close the screen and open it again, it crashes - I found a way to clear it in view model `onCleared`, so I do `componentContext.stateKeeper.unregister(key)` - and that fixes the problem.

But now I want to use `retainedComponent` so I don't have to use `InstanceKeeper`. In this case when I try to unregister it with `stateKeeper.unregister(key)`, it crashes with the message "No supplier is registered with the key", but if I don't unregister and reopen the screen, it crashes with the message "SavedStateProvider with the given key is already registered".

I think the correct thing to do here is to pass valid values of `lifecycle`/`savedStateRegistry`/`localViewModelStore`, which will allow component to be correctly destroyed. I built a composable to do this, but I had to copy the `retainedComponent` source code into my project.

Everything seems to work as it should, but I wonder if I'm missing something and if not - if this composable can be added to the Decompose source code or if `retainedComponent` can be made public for such cases.

```kotlin
@Composable
fun <T> rememberRetainedComponent(
    key: String,
    factory: (ComponentContext) -> T,
): T {
    val activity = LocalContext.current.findActivity() as ComponentActivity

    val lifecycleOwner = LocalLifecycleOwner.current
    val localViewModelStoreOwner = LocalViewModelStoreOwner.current
    val savedStateRegistryOwner = LocalSavedStateRegistryOwner.current

    return remember(lifecycleOwner, localViewModelStoreOwner, savedStateRegistryOwner, activity) {
        object : LifecycleOwner,
            SavedStateRegistryOwner by savedStateRegistryOwner,
            ViewModelStoreOwner by (localViewModelStoreOwner ?: activity) {
            override val lifecycle: Lifecycle
                get() = lifecycleOwner.lifecycle
        }.retainedComponent(
            key = key,
            onBackPressedDispatcher = activity.onBackPressedDispatcher,
            isChangingConfigurations = { activity.isChangingConfigurations },
            factory = factory,
        )
    }
}
```

**Comment by arkivanov** [comment]
Thanks for the use case!

> How to manually destroy component created with `retainedComponent`?

It's not possible, because `retainedComponent` is retained and destroyed automatically.

> if retainedComponent can be made public for such cases

For now, I would like to keep that function private, unless there are stronger use cases or more demand. The the bigger the API surface is, the more difficult it is to maintain.

> if this composable can be added to the Decompose source code

Same here. For now it looks pretty easy to implement manually. If there is demand, we could do it later.

Your example looks pretty good, just some minor improvements.

```kotlin
@Composable
fun <T> rememberRetainedComponent(
    key: String,
    factory: (ComponentContext) -> T,
): T {
    val activity = LocalContext.current.findActivity() as ComponentActivity
    val viewModelStoreOwner = LocalViewModelStoreOwner.current ?: activity
    val savedStateRegistryOwner = LocalSavedStateRegistryOwner.current
    val onBackPressedDispatcherOwner = LocalOnBackPressedDispatcherOwner.current ?: activity

    return remember(key, viewModelStoreOwner, savedStateRegistryOwner, activity) {
        object : SavedStateRegistryOwner by savedStateRegistryOwner, ViewModelStoreOwner by viewModelStoreOwner {}.retainedComponent(
            key = key,
            onBackPressedDispatcher = onBackPressedDispatcherOwner.onBackPressedDispatcher,
            isChangingConfigurations = { activity.isChangingConfigurations },
            factory = factory,
        )
    }
}
```

Or maybe you will find the following option even more useful. I didn't try it but I think it should work.

```kotlin
@Composable
fun <T> rememberRetainedComponent(
    key: String,
    factory: (ComponentContext) -> T,
): T {
    val lifecycleOwner = LocalLifecycleOwner.current
    val lifecycle = remember(lifecycleOwner) { lifecycleOwner.essentyLifecycle() }
    val savedStateRegistryOwner = LocalSavedStateRegistryOwner.current
    val stateKeeper = remember(savedStateRegistryOwner) { savedStateRegistryOwner.stateKeeper() }
    val holder = viewModel(key = key) { RetainedComponentHolder(savedState = stateKeeper.consume(key = key), factory = factory) }

    DisposableEffect(lifecycle, holder) {
        lifecycle.subscribe(holder.lifecycle)
        onDispose { lifecycle.unsubscribe(holder.lifecycle) }
    }

    DisposableEffect(stateKeeper, holder) {
        stateKeeper.register(key = key) { holder.stateKeeper.save() }
        onDispose { stateKeeper.unregister(key = key) }
    }

    BackHandler(enabled = holder.hasEnabledBackCallback) {
        holder.onBackPressedDispatcher.onBackPressed()
    }

    return holder.component
}

private class RetainedComponentHolder<out T>(
    savedState: ParcelableContainer?,
    factory: (ComponentContext) -> T,
) : ViewModel() {
    val lifecycle: LifecycleRegistry = LifecycleRegistry()
    val stateKeeper: StateKeeperDispatcher = StateKeeperDispatcher(savedState = savedState)
    private val instanceKeeper: InstanceKeeperDispatcher = InstanceKeeperDispatcher()

    var hasEnabledBackCallback: Boolean by mutableStateOf(false)
        private set

    val onBackPressedDispatcher: OnBackPressedDispatcher = OnBackPressedDispatcher(
        fallbackOnBackPressed = null,
        onHasEnabledCallbacksChanged = { hasEnabledBackCallback = it },
    )

    val component: T = factory(
        DefaultComponentContext(
            lifecycle = lifecycle,
            stateKeeper = stateKeeper,
            instanceKeeper = instanceKeeper,
            backHandler = BackHandler(onBackPressedDispatcher),
        )
    )

    override fun onCleared() {
        instanceKeeper.destroy()
    }
}
```

**Comment by PhilipDukhov** [comment]
Thanks, your updated version looks good!

Ok, it's not a big problem to have 100 LOC duplicated in my codebase.
