### ISSUE TITLE
Considering publishing the iOS 'DecomposeHelpers' as a framework

### ISSUE THREAD

**Issue by chrisbanes** [arkivanov/Decompose#455]
The '[DecomposeHelpers](https://github.com/arkivanov/Decompose/tree/master/sample/app-ios/app-ios/DecomposeHelpers)' in the iOS sample are very useful, but I'd rather not have to copy them into my project. Have you thought about publishing them as an SPM library?

**Comment by arkivanov** [comment]
Yeah. As [mentioned in the docs](https://arkivanov.github.io/Decompose/getting-started/quick-start/#what-is-statevalue), I couldn't find a way of publishing those helpers. Also see #206.

If I understand it correctly, the published SPM library wouldn't be able to communicate with your exported shared framework that exports Decompose Kotlin types. Those types will be treated as different ones. This is essentially the same issue as exporting two Kotlin frameworks (see the [article](https://touchlab.co/multiple-kotlin-frameworks-in-application/)).

Please let me know if you have any ideas how this could actually work!

**Comment by chrisbanes** [comment]
Ahhhh makes sense! Feel free to close this as a dupe.
