### ISSUE TITLE
[3.0.0] ChildNavState.Status for STARTED state

### ISSUE THREAD

**Issue by DanilKolesGitHub** [arkivanov/Decompose#465]
I have a problem when implementing a custom NavState. 
I need to implement NavState similar to StackNavState. However, the components that are in the backstack must be in the STARTED state. It would be convenient to use ChildNavState.Status. However, there is no status for this lifecycle state.
Now there is only such a correspondence of statuses and lifecycle states:
DESTROYED -> DESTROYED
CREATED -> INACTIVE
STARTED -> nothing
RESUMED -> ACTIVE
Is it possible to add one more status in future releases?

**Comment by arkivanov** [comment]
Thanks for the request! This would be a breaking API, it will only be possible to add in version `3.0.0`.

Currently, you can try wrapping your child `ComponentContext` with the following wrapper. Let me know if it works for you.

```kotlin
class UnstoppableComponentContext(
    private val delegate: ComponentContext,
) : ComponentContext by delegate {
    override val lifecycle: LifecycleRegistry = LifecycleRegistry()

    init {
        delegate.lifecycle.subscribe(
            object : Lifecycle.Callbacks {
                override fun onCreate() {
                    lifecycle.start()
                }

                override fun onStart() {
                    lifecycle.start()
                }

                override fun onResume() {
                    lifecycle.resume()
                }

                override fun onPause() {
                    lifecycle.pause()
                }

                override fun onStop() {
                    // no-op
                }

                override fun onDestroy() {
                    lifecycle.destroy()
                }
            }
        )
    }
}

```
