### ISSUE TITLE
[3.0.0] Migrate to kotlinx-serialization

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#470]
See: https://github.com/arkivanov/Essenty/issues/102
See: https://youtrack.jetbrains.com/issue/KT-58892

**Comment by YektaDev** [comment]
**A small idea:** I don't know if `Json` instances are _heavy_ or not, or whether this is a safe idea. But, if they **are** heavy, it would be nice to be able to have an optional parameter `json: Json? = json` in the overloads which take a `serializer: KSerializer<C>?`; so that one can reuse a `json` instance.
But I guess it's not safe, particularly because of the need for `allowStructuredMapKeys = true`.

**Comment by arkivanov** [comment]
Thanks! I think there is [only one Json instance](https://github.com/arkivanov/Essenty/blame/b7412669129a21ea91ac4908f14275f44b53c7e4/state-keeper/src/commonMain/kotlin/com/arkivanov/essenty/statekeeper/Utils.kt#L7) per app?

**Comment by YektaDev** [comment]
I found `com.arkivanov.decompose.router.SavedData.json` from IDE, but I can't find it here. It's updated I assume.
btw, your responding speed is unbelievable (⚆_⚆)

**Comment by arkivanov** [comment]
Ah yes, this one is a [second instance](https://github.com/arkivanov/Decompose/blob/5e0a097663bdf12e1bd9af23abe099e89efd926c/decompose/src/commonMain/kotlin/com/arkivanov/decompose/router/SavedData.kt#L11). But it's temporary until v3.0.0. So currently there are two instances per app, and later will be just one.

**Comment by mvarnagiris** [comment]
It would still be good to somehow allow to pass Json or at least `SerializersModule`, because if your `Config` depends on some `@Contextual` serialization, then those classes right now cannot be serialized. Or maybe I'm doing something wrong.

I have this:
```kotlin
@Serializable
data class RouteConfig(
    val route: @Contextual RouteData, // RouteData is an interface
    ...
)
```

I have my own `Json` instance that has polymorphic serialization for `RouteData` registered:
```kotlin
Json {
    serializersModule = SerializersModule {
        polymorphic(RouteData::class) {
            subclass(Actual1RouteData::class)
            subclass(Actual2RouteData::class)
        }
    }
}
```

When creating child stack I thought this would do the trick, but it does not work:
```kotlin
private val stack = childStack(
    serializer = myJsonInstance.serializersModule.serializer(),
    ...
)
```

When stack is saved I get
```
kotlinx.serialization.SerializationException: Class 'Actual1RouteData' is not registered for polymorphic serialization in the scope of 'RouteData'.
To be registered automatically, class 'Actual1RouteData' has to be '@Serializable', and the base class 'RouteData' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'Actual1RouteData' explicitly in a corresponding SerializersModule.
```

If I try to serialize it manually using my `Json` instance then all is good

**Comment by arkivanov** [comment]
Thanks for the use case! I will think about it, but for now I would say that `@Contextual` is not supported. Currently, this is 100% equivalent to `Parcelable/Parcelize`, where you can only have types known at compile time. Or use lazy deseralization via `ParcelableContainer`, and there will be `SerializableContainer` later in v3.0.

**Comment by mvarnagiris** [comment]
You mean I should use childStack with `Parcelable`s, by wrapping my `Config` into a Parcelable wrapper and doing my own json serialization inside?

**Comment by mvarnagiris** [comment]
The reason why my Config needs to be an interface is that I have a multi module structure, where each feature lives inside it's own module and defines it's own router Configs. So my base Config class cannot be sealed.

To my own question above: I see there is childStack that takes saveStack function where I can do it manually.

**Comment by arkivanov** [comment]
Decompose version 2.2.x still interops via Parcelable, this is temporary for smoother transition to kotlinx-serialization. In version v3.0 there will be proper support of kotlinx-serialization and all Parcelable APIs will be removed. So currently there is no way of using `SerializableContainer` because it doesn't exist yet.

The reason why `Json` is private is because it needs lazy deserialization. Decompose is not aware of actual configuration classes, and so requires a `Serializer` for every configuration class. When the state is restored, it gets deserialized at the time of creating the root `ComponentContext` (actually when creating the root `StateKeeper`), before even the root component is created. And so configurations can't be deserialized immediately, because there `Serializers` are not specified yet. So on each stack level, the corresponding `StateKeeper` has to serialize its state into an internal structure (currently it's `ByteArray`), and then deserialize on demand when the `Serializer` is specified.

The question here is how would you handle this case with `Parcelable/Parcelize`? Probably, by using `TypeParceler` annotations. I think a similar approach could be taken with `kotlinx-serialization`.

You could consider making `RouteData` a sealed interface, this would make it serializable automatically. If this is not possible (e.g. implementations are in different modules), then you can also try writing your own `Serializer` for `RouterData` at the place where you use `Child Stack`.

```kotlin
@Serializable
data class RouteConfig(
    val route: @Serializable(with = RouteDataSerializer::class) RouteData,
)

object RouteDataSerializer : KSerializer<RouteData> {
    override val descriptor: SerialDescriptor = Surrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: RouteData) {
        encoder.encodeSerializableValue(
            serializer = Surrogate.serializer(),
            value = when (value) {
                is Actual1RouteData -> Surrogate.Actual1(data = value)
                is Actual2RouteData -> Surrogate.Actual2(data = value)
                else -> error("Unsupported type: $value")
            },
        )
    }

    override fun deserialize(decoder: Decoder): RouteData =
         decoder.decodeSerializableValue(Surrogate.serializer()).data

    @Serializable
    private sealed interface Surrogate {
        val data: RouteData

        @Serializable
        class Actual1(override val data: Actual1RouteData): Surrogate

        @Serializable
        class Actual2(override val data: Actual2RouteData): Surrogate
    }
}
```

**Comment by mvarnagiris** [comment]
But if I'm not mistaken everything would work fine now and later if we could provide `SerializersModule` for you to use when serializing.
```kotlin
childStack(
    serializer = serializer(),
    serializersModule = SerializersModule {
        polymorphic(RouteData::class) {
            subclass(Actual1RouteData::class)
            subclass(Actual2RouteData::class)
        }
    }
    ...
)
```

**Comment by mvarnagiris** [comment]
You would need to set that module on your Json instance

**Comment by arkivanov** [comment]
> You would need to set that module on your Json instance

How this can be done? Currently, the Json instance is stored in a top level property. Moreover, there are two Json instances, one in Essenty and one in Decompose. But the Decompose Json instance is temporary, though.

This is because the serialization process begins before the Root component is created. And we also don't want adding the same module multiple times.

**Comment by mvarnagiris** [comment]
Maybe some global configuration for Json?
```kotlin
Essenty.setSerializersModule(...)

internal val essentyJson: Json by lazy {
    Json {
        allowStructuredMapKeys = true
        serializersModule = Essenty.JsonConfig.serializersModule // This would be some global configuration
    }
}
```

**Comment by mvarnagiris** [comment]
You say that serialization starts before root component is created. Could you point me to a file where serialization starts?

**Comment by arkivanov** [comment]
Thanks for the idea! I tend to avoid global configurations, as it adds timing requirement. E.g. you must define all possible modules before any serialization actions. You may have some modules accessed later and so it's too late to register modules. Or your app must grab all serialization modules from all components, which I really would like to avoid.

I will see if we can create Json each time and apply the provided module. Otherwise, there is a solution with custom serializers.

Btw this looks like a nice feature request for kotlinx-serialization. There could be an annotation to specify polymorphic serializers for a base type.

**Comment by mvarnagiris** [comment]
There is an open issue open for kotlinx-serialization regarding global configuration, but I don't think it's coming any time soon.

But they already support polymorphic serializers for base type. For sealed class and sealed interface you just need to mark your base as `@Serializable`. For abstract classes and interface you need to do it like this
```kotlin
polymorphic(RouteData::class) {
   subclass(Actual1RouteData::class)
   subclass(Actual2RouteData::class)
}
```

Annotation on base interface or abstract class is not possible, because in that module we might not have all classes that extend it.

Regarding essenty global configuration - yeah I completely get it that his is not a nice solution. It was just quick off the top of my head without going deep into the source code. If Json creation is not "heavy" then technically it can be created right before it is needed - in this case we can pass our `SerializersModule`. If my rough understanding is correct really serialization is triggered when app state is saved and deserialization is when app state is restored. So really it would be just twice per session.

**Comment by mvarnagiris** [comment]
In the meantime I resolved it like this
```kotlin
@Parcelize
private data class SerializedRoutes(val routesJson: List<String>) : Parcelable // here each serialized route is in the list

childStack(
    ...,
    saveStack = { routes ->
        val json = getMyJsonInstance()
        ParcelableContainer(SerializedRoutes(routes.map { json.encodeToString(it) }))
    },
    restoreStack = { parcelableContainer ->
        val json = getMyJsonInstance()
        val serializedRoutes = parcelableContainer.consume(SerializedRoutes::class)
        serializedRoutes?.routesJson?.map { json.decodeFromString<MyRouteConfig>(it) }
    },
)
```

**Comment by arkivanov** [comment]
> Could you point me to a file where serialization starts?

Sure! So the entire process begins when you call `Activity#defaultComponentContext`, which [creates](https://github.com/arkivanov/Decompose/blob/62767e6a14577c95ffed121f6c4de66f433c6e0e/decompose/src/androidMain/kotlin/com/arkivanov/decompose/DefaultComponentContextBuilder.kt#L25) Android-specific implementation of `StateKeeper`, which [consumes](https://github.com/arkivanov/Essenty/blob/b7412669129a21ea91ac4908f14275f44b53c7e4/state-keeper/src/androidMain/kotlin/com/arkivanov/essenty/statekeeper/AndroidExt.kt#L20) the previously saved state from the `Bundle`. But at this point we don't know all the child types, e.g. custom `Parcelable` or `Serializable` configurations, or any custom state saved via `StateKeeper`. And keep in mind the requirement to avoid global module collections. So Essenty wraps all such data into `ParcelableContainer` (on Android it [uses Bundle for laziness](https://github.com/arkivanov/Essenty/blob/master/parcelable/src/androidMain/kotlin/com/arkivanov/essenty/parcelable/AndroidParcelableContainer.kt)), and deserializes it on demand when you call `StateKeeper#consume`. With `Parcelable` you must supply `KClass<T>`, so that Essenty can set it to the Bundle inside the corresponding `ParcelableContainer`. With `Serializable`, you must specify a serializer for the same reason.

**Comment by arkivanov** [comment]
After some investigation, I think it would be possible to supply an optional module and create a new instance of Json if the module is supplied, and use the default shared one if it's not. I will check this further.

**Comment by arkivanov** [comment]
The addition of the `module` argument is currently blocked by https://github.com/Kotlin/kotlinx.serialization/issues/2484.

**Comment by mvarnagiris** [comment]
To me it seems like that issue is not with the custom serializers module, but the structure of `Some` class. In that case maybe a special serializer needs to be provided for it. It's up to the user of Decompose to provide `SerializersModule` that can handle their `Config` classes.

**Comment by arkivanov** [comment]
That looks like a bug in the streaming API. E.g. it works with `encodeToString`/`decodeFromString`, it also works without specifying the module and with including `Some` into `Value` directly (instead of `SomeInterface`, i.e. no polymorphism). Only fails when using `encodeToStream`/`decodeFromStream` and polymorphism + module. There are failing tests in Essenty because of this.

**Comment by arkivanov** [comment]
I have also discovered another possible solution for custom serializer modules, but I'm not sure yet whether it's correct or not. Copying it here from https://kotlinlang.slack.com/archives/C7A1U5PTM/p1698266978922789.

In Essenty we could define the following class (we might need to find another name though, since there is another `PolymorphicSerializer` in kotlinx-serialization).

```kotlin
@OptIn(ExperimentalSerializationApi::class)
open class PolymorphicSerializer<T : Any>(
    private val baseClass: KClass<T>,
    private val module: SerializersModule,
) : KSerializer<T> {
    override val descriptor: SerialDescriptor =
        buildClassSerialDescriptor("PolymorphicSerializer") {
            element<String>("type")
            element("value", ContextualSerialDescriptor)
        }

    override fun serialize(encoder: Encoder, value: T) {
        val serializer = requireNotNull(module.getPolymorphic(baseClass, value))
        encoder.encodeStructure(descriptor) {
            encodeStringElement(descriptor, 0, serializer.descriptor.serialName)
            encodeSerializableElement(descriptor, 1, serializer, value)
        }
    }

    override fun deserialize(decoder: Decoder): T =
        decoder.decodeStructure(descriptor) {
            var className: String? = null
            var value: T? = null

            while (true) {
                when (val index = decodeElementIndex(descriptor)) {
                    0 -> className = decodeStringElement(descriptor, index)

                    1 -> {
                        val actualClassName = requireNotNull(className)
                        val serializer = requireNotNull(module.getPolymorphic(baseClass, actualClassName))
                        value = decodeSerializableElement(descriptor, 1, serializer)
                    }

                    CompositeDecoder.DECODE_DONE -> break

                    else -> error("Unsupported index: $index")
                }
            }

            requireNotNull(value)
        }

    private object ContextualSerialDescriptor : SerialDescriptor {
        override val elementsCount: Int = 0
        override val kind: SerialKind = SerialKind.CONTEXTUAL
        override val serialName: String = "Value"

        override fun getElementAnnotations(index: Int): List<Annotation> = elementNotFoundError(index)
        override fun getElementDescriptor(index: Int): SerialDescriptor = elementNotFoundError(index)
        override fun getElementIndex(name: String): Int = CompositeDecoder.UNKNOWN_NAME
        override fun getElementName(index: Int): String = elementNotFoundError(index)
        override fun isElementOptional(index: Int): Boolean = elementNotFoundError(index)

        private fun elementNotFoundError(index: Int): Nothing {
            throw IndexOutOfBoundsException("Element at index $index not found")
        }
    }
}
```

Then that can be used as follows.

```kotlin
    // In another module
    interface RouteData

    @Serializable
    data class Actual1RouteData(val payload: String) : RouteData

    @Serializable
    data class Actual2RouteData(val payload: String) : RouteData

    class RouteDataSerializer : PolymorphicSerializer<RouteData>(
        baseClass = RouteData::class,
        module = SerializersModule {
            polymorphic(RouteData::class) {
                subclass(Actual1RouteData::class, Actual1RouteData.serializer())
                subclass(Actual2RouteData::class, Actual2RouteData.serializer())
            }
        }
    )

    @Serializable
    data class RouteConfig(
         val route: @Serializable(RouteDataSerializer::class) RouteData,
    )
```

This seems to work fine, there is no need to change the API, and the API remains simpler. Though I'm not sure if it's OK that it's not possible to introspect my PolymorphicSerializer's descriptor, as it contains a contextual element and the module is not registered anywhere. I will need to investigate this further.

**Comment by arkivanov** [comment]
Essenty [1.3.0-alpha03](https://github.com/arkivanov/Essenty/releases/tag/1.3.0-alpha03) added the experimental `polymorphicSerializer` function. Decompose [2.2.0-alpha04](https://github.com/arkivanov/Decompose/releases/tag/2.2.0-alpha04) depends on Essenty `1.3.0-alpha03`.
