### ISSUE TITLE
Confusion about name for parcelize-darwin plugin

### ISSUE THREAD

**Issue by desai-tapan** [arkivanov/Decompose#477]
I am trying to add Decompose to my Compose Multiplatform project. During the setup I am getting confused about the actual plugin name for `parcelize-darwin`

In Essenty's readme the name of the plugin is mentioned as [parcelize-darwin](https://github.com/arkivanov/Essenty)
```
plugins {
    id("kotlin-parcelize") // Apply the plugin for Android
    id("parcelize-darwin") // Optional, only if you need support for Darwin targets
}

// Add the dependency, typically under the commonMain source set
implementation("com.arkivanov.essenty:parcelable:<essenty_version>")
```

And in the Parcelize readme it is mentiond as [com.arkivanov.parcelize.darwin](https://github.com/arkivanov/parcelize-darwin)

```
// Root build.gradle

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath("com.arkivanov.parcelize.darwin:gradle-plugin:<version>)
    }
}

// Module's build.gradle

plugins {
    id("com.arkivanov.parcelize.darwin")
}
```

So which is the correct one?

**Comment by arkivanov** [comment]
The correct way is: `id("com.arkivanov.parcelize.darwin")`. I have updated the readme for Essenty. Thanks!
