### ISSUE TITLE
in 1.3.0 alpha, with Parcelize Deprecated, why android still typealiases to Parcelable ?

### ISSUE THREAD

**Issue by Shabinder** [arkivanov/Decompose#489]
Fn's like `childSlot` expect the configs to be subtype of Parcelable.

Now after **deprecating** `@Parcelize`, and shifting over to **kotlinx.serialization** why does still android side `typealiases` to `android.os.Parcelable` ?

since having configs and navigation in common without deprecated @Parcelize, throws error:

> Class is not abstract and does not implement abstract base class member public abstract fun describeContents(): Int

Whats the recommended way forwards ?

**Comment by arkivanov** [comment]
There are new function overloads for navigation with `kotlinx-serialization`. Please see the docs: https://arkivanov.github.io/Decompose/navigation/slot/overview/#example

**Comment by Shabinder** [comment]
aah missed the table and tab bar in documentation earlier  for newer usage.
Thanks 👍
