### ISSUE TITLE
Cancel subscription based observe {} in the synchronously sent current value

### ISSUE THREAD

**Issue by Burtan** [arkivanov/Decompose#516]
Hi,
subscription {} is now deprecated in favor of observe {} which returns a Cancellation object. This causes problems when you want to cancel it in the event block when being called synchronously with the current value.

```
var subscription: Cancellation? = null
subscription = observe { value ->
    // do something
    subscription?.cancel()
}
```

The example does not work on the current value as subscription has not been created, yet. Maybe the event block should also provide the subscription object?

```
observe { value, subscription ->
    // do something
    subscription?.cancel()
}
```

**Comment by arkivanov** [comment]
Yes, this is a known limitation. The same is applicable to libraries like RxJava, Coroutines, etc. It's a common practice to return a cancellation token. Adding the `subscription/cancellation` parameter to the callback would make the API more verbose, also it would prevent using method references like `value.observe(::onValue)`. Though, we could thing about adding an overload method with a different name.

If you only need to unsubscribe unconditionally when the first value is received, then you can just read the value as follows.

```kotlin
val currentValue = value.value
// do something
```

Otherwise you could define something like:

```kotlin
class LateInitCancellation : Cancellation {
    fun set(cancellation: Cancellation) {
        // ...
    }

    override fun cancel() {
        // ...
    }
}
```

But keep in mind that it should be thread-safe. Perhaps, we could add it to the library.

**Comment by Burtan** [comment]
My usecase is waiting for a defined childStack state in component testing. It works this way, just thought about it being easier with a subscription object inside the event handler.

```
suspend inline fun <reified T> Value<ChildStack<*, *>>.awaitChild(): T {
    // return directly when the initial value fits the correct child type
    // don't use the immediate observe value because subscription is still null then and cannot be
    // cancelled
    if (value.active.instance is T)
        return value.active.instance as T

    var subscription: Cancellation? = null
    return suspendCoroutine {
        subscription = observe { value ->
            if (value.active.instance is T) {
                subscription?.cancel()
                it.resume(value.active.instance as T)
            }
        }
    }
}
```

**Comment by arkivanov** [comment]
Thanks for the use case! Since you are using coroutines, perhaps you could do something as follows? I haven't test it, just from the top of my head.

```kotlin
fun <T> Value<T>.asFlow(): Flow<T> =
    channelFlow { 
        val cancellation = observe(channel::trySend)
        awaitClose(cancellation::cancel)
    }

suspend inline fun <reified T> Value<ChildStack<*, *>>.awaitChild(): T =
    asFlow()
        .map { it.active.instance }
        .filterIsInstance<T>()
        .first()
```

**Comment by Burtan** [comment]
> Thanks for the use case! Since you are using coroutines, perhaps you could do something as follows? I haven't test it, just from the top of my head.
> 
> ```kotlin
> fun <T> Value<T>.asFlow(): Flow<T> =
>     channelFlow { 
>         val cancellation = observe(channel::trySend)
>         awaitClose(cancellation::cancel)
>     }
> 
> suspend inline fun <reified T> Value<ChildStack<*, *>>.awaitChild(): T =
>     asFlow()
>         .map { it.active.instance }
>         .filterIsInstance<T>()
>         .first()
> ```

Looks cleverer than my solution as there is no possibility to miss the cancellation. In my solution when the value changes between the immediate value check and the first event block, it could miss the cancellation.
