### ISSUE TITLE
Runtime error with compose web

### ISSUE THREAD

**Issue by alexzhirkevich** [arkivanov/Decompose#561]
Hi. Getting this runtime error for each symbol from extensions-compose-jebtrains for js/canvas. Any ideas? 
Kotlin 1.9.21, compose 1.6.0-alpha01, decompose 2.2.0-compose-experimental

`
Function 'stackAnimator' can not be called: No function found for symbol 'com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation/stackAnimator|stackAnimator(androidx.compose.animation.core.FiniteAnimationSpec<kotlin.Float>;kotlin.Function5<kotlin.Float,com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.Direction,kotlin.Function3<androidx.compose.ui.Modifier,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>){}[0]'
captureStack@
IrLinkageError@
throwLinkageError@
main$lambda@
`

```kotlin
@OptIn(ExperimentalComposeUiApi::class)
fun main() {
//    WebApp()
    onWasmReady {
        stackAnimator { factor, direction, content ->  }

        CanvasBasedWindow {
            Text("TEST")
        }
    }
}

```

```kotlin
@Suppress("DSL_SCOPE_VIOLATION")
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose)
}

kotlin {
    js(IR){
        browser()
        binaries.executable()
    }

    sourceSets {
        jsMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.material)
            implementation(libs.decompose.core)
            implementation(libs.decompose.compose)
//            implementation(project(":shared"))
        }
    }
}

compose.experimental.web.application{}
```

**Comment by arkivanov** [comment]
Thanks for the report. I tried quickly but couldn't reproduce the issue. Could you please try Compose version `1.5.10` just to check if it works? This might be a breaking change in Compose for JS compiler.

**Comment by alexzhirkevich** [comment]
1.5.11 works good for empty project. But unfortunately 1.6.0 contains an important compiler fix my project doesn't compile without. 

Getting compile error on 1.5.11 and runtime error on 1.6.0-alpha 👍 Casual compose-for-web experience

**Comment by arkivanov** [comment]
Thanks for confirming! I'm going to release v3.0.0-alpha01 soon. Perhaps, I could update Compose to latest alpha version in that release.

**Comment by arkivanov** [comment]
Version [3.0.0-alpha01](https://github.com/arkivanov/Decompose/releases/tag/3.0.0-alpha01) based on Multipaltform Compose `1.6.0-alpha01` is released. Could you please try?

**Comment by alexzhirkevich** [comment]
Works perfect. Thanks! <3

**Comment by arkivanov** [comment]
Awesome! Closing the issue for now.
