### ISSUE TITLE
Use LocalProvider for emptyStackAnimation

### ISSUE THREAD

**Issue by LionZXY** [arkivanov/Decompose#570]
Right now you can do nested Children graphs in Compose, but then you have to manually set things like `animation: StackAnimation`

I think this is wrong, I think instead of a hardcoded parameter should use LocalProvider:

```kotlin
val LocalStackAnimation = compositionLocalOf<StackAnimation<Any, Any>> { EmptyStackAnimation() }
```

And instead of `emptyStackAnimation()` call `LocalStackAnimation.current`

**Comment by arkivanov** [comment]
Thanks for the idea! I have thought about it, I think we can add it. Also thanks for the PR, I have left some comments.
