### ISSUE TITLE
Paging Library not working 3.0.0-alpha (only ios target)

### ISSUE THREAD

**Issue by taetae98coding** [arkivanov/Decompose#582]
multiplatform-paging not working. (only ios target not working)
- add or delete item list LazyColumn doesn't update.
- but 2.2.0 works fine

https://github.com/cashapp/multiplatform-paging
- [3.3.0-alpha02-0.4.0](https://github.com/cashapp/multiplatform-paging/releases/tag/3.3.0-alpha02-0.4.0)

**Comment by arkivanov** [comment]
Is it related to Decompose? Could you describe the issue in more detail?

**Comment by taetae98coding** [comment]
I just write sample code. It has only three kotlin files.
- https://github.com/taetae98coding/DecomposePaging

`main` branch use decompose 3.0.0-alpha04
- android working
- ios not working
- https://github.com/taetae98coding/DecomposePaging

`fix_paging` branch use decompose 2.2.2-compose-experimental
- android working
- ios working
- it has only version change commit
- https://github.com/taetae98coding/DecomposePaging/tree/fix_paging

**Comment by arkivanov** [comment]
Thanks for the producer. This indeed looks unrelated to Decompose, please file an issue for the paging library.

The following code is also not working without any use of Decompose.

```kotlin
@Composable
fun MainRoute(
    modifier: Modifier = Modifier,
) {
    val viewModel = remember { MainViewModel() }

    MaterialTheme {
        MainScreen(
            modifier = modifier,
            pagingItems = viewModel.pagingData.collectAsLazyPagingItems(),
            onAdd = viewModel::add
        )
    }
}
```

**Comment by arkivanov** [comment]
I think the issue is because Decompose `3.0.0-alpha04` depends on Compose `1.6.0-alpha01`, whereas Decompose `2.2.2` depends on Compose `1.5.11`. It looks like the Paging library `3.3.0-alpha02-0.4.0` works with Compose `1.5.11`, but doesn't work with Compose `1.6.0-alpha01`. Please file an issue for the Paging library instead.
