### ISSUE TITLE
Any particular reason why T in Value<T> extends Any instead of Any?

### ISSUE THREAD

**Issue by asuras-coding** [arkivanov/Decompose#584]
Hey there,

I am trying out your lib with compose multiplatform for a side project and it's been working really smooth so far.
But I can not have a Value which can hold a null value which I need as init-Value, e.g. if I want to display something only if its there.
Reading the code I've seen that Value just cant use a nullable type and now i am curious why that is. Any technical restrictions or did it just happen to be like this? The workaround is creating a wrapper class with an optional value, which makes it work as intended, but also bloats the code

Greetings :)

**Comment by arkivanov** [comment]
Hey! Yes, this was designed so on purpose. Please see https://github.com/arkivanov/Decompose/discussions/55.

**Comment by asuras-coding** [comment]
Thanks for the fast response.

I don't really know anything about swift/objc, but it looks a little like platform types in java/kotlin interaction (but also different).
So if you have Value<T: Any> the export makes the Value<String> in swift not nullable, but if you define Value<T> is would be nullable?

I am also thinking about an OptionalValue<T: Any?> next to Value<T: Any> so a wrapper is not needed and its minimal duplication. The value-property could then also return T? to make it visible that this observable value holder is meant to hold values that can be null.

**Comment by arkivanov** [comment]
Yes, if we define `Value<T>` in Kotlin, then in Swift it will be always nullable, regardless of the actual type. E.g. a property like `val value: Value<String>` will be nullable in Swift.

I also considered `OptionalValue`, but we would also need `MutableOptionalValue`, etc. And this would only be used in consuming projects, the Decompose library don't need it. That's said, you can create `OptionalValue` on your own, or just use `StateFlow` from coroutines or `BehaviorSubject` from Reaktive, etc.
