### ISSUE TITLE
Live Edit or @Preview Not working. Are they possible?

### ISSUE THREAD

**Issue by adrianegraphene** [arkivanov/Decompose#591]
**Goals**
 To work in decompose, while being able to see Android UI Changes in Live Edit, or @Preview.

**Using**
Decompose 2.1.0-compose-experimental
Android Studio 2023.1.1 Patch 1

**Targets**
Android, iOS, 

Before I take the simplest answer and assume that both "Live Edit" and "@Preview" do not work in Android emulators that are running from a Decompose codebase... I figured I'd ask here + share what I've tried. 

Live Edit does not work in Kotlin files in commonMain, but. Nor does Preview.  Is this expected? 

### My observations
**Live Edit**
Works in androidMain, but does not work in commonMain, where most Kotlin files are.

- Test case:  
  - Change size of image in a composable in commonMain, with emulator running and live edit on.
- Issue:  
  - Live Edit shows "Out of Date". Hovering over it shows "Test sources not supported: MyFileName.kt"
- Possible Reasons
  - .iml files in .idea folder do not correctly list commonMain in their "pureKotlinFiles"
  - multiple .iml files instead of one

Happy to share my files here, but they're kind of verbose. Figured I'd just ask first, if anyone's gotten Live Edit working in any version of Decompose.

**Comment by arkivanov** [comment]
I believe this issue is unrelated to Decompose. I'm pretty sure live previews (an actually just normal previews) are officially not supported in commonMain. I think this feature is being tracked here: https://github.com/JetBrains/compose-multiplatform/issues/2045.

**Comment by adrianegraphene** [comment]
that is correct, just wanted to see if anyone had gotten it working . That link you provided is perfect. I'll follow that and close this. Thank you!

**Comment by arkivanov** [comment]
It is possible to have normal (not live) previews in commonMain if you have the `jvm` (Compose for Desktop) target enabled. You need to define [expect class Preview](https://github.com/arkivanov/Decompose/blob/master/sample/shared/compose/src/commonMain/kotlin/androidx/compose/desktop/ui/tooling/preview/Preview.kt), then you can [write your previews as usual](https://github.com/arkivanov/Decompose/blob/78f737a5a08930fb53b8af6b549586bec446b506/sample/shared/compose/src/commonMain/kotlin/com/arkivanov/sample/shared/counters/counter/CounterContent.kt#L89). Keep in mind that you need [Compose Multiplatform IDE Support](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support) plugin installed.

**Comment by adrianegraphene** [comment]
That was my understanding too, from reading that previous. But I'm very happy to see the advice you've provided here too, as well as the link to the plugin (which I did not have).  I will follow that and things should be OK with preview. Thank you so much!
