### ISSUE TITLE
Can the documentation be improved for newcomers?

### ISSUE THREAD

**Issue by zveljkovic** [arkivanov/Decompose#600]
Hi and thank you for the great library! I am experiencing issues trying to set it up, as I am new to Kotlin Multiplatform and project structure. One thing that could greatly help would be short tips on location for the changes and import section to not be removed on code samples. 

Example: getting-started/installation
There is a mention for inclusion of 
`implementation("com.arkivanov.decompose:decompose:<version>")`
but that doesn't say in which build.gradle.ts to add it. I have created the project with https://kmp.jetbrains.com/ and I have three such files.  This one probably go in commonMain but what about extensions-android? Is it in shared/build.gradle.kts commonMain, androidMain or somewhere in composeApp/build.gradle.kts? 

Also when following tutorials about navigation there is no file path included where the code need to be created. This guesswork is now blocking me as I cannot figure out what to do to solve missing Children reference. Also please include imports in the code samples so we can verify we put everything correctly.

This will be a quick update to doc and will help immensely when trying out the lib.

**Comment by arkivanov** [comment]
Thanks for feedback! The documentation kind of implies some knowledge of KMP, Gradle, source sets, etc. But there is always room for improvement.

> There is a mention for inclusion of ... but that doesn't say in which build.gradle.ts to add it.

This has to be placed in the `build.gradle.kts` file of the module where you are going to use Decompose. It highly depends on the actual project and use cases. When writing KMP, there are usually two relevant Gradle modules: `shared` and `android-app`. But there may be another module structure. How would you like the docs to be improved here?

> This one probably go in commonMain

This again depends. In a shared module - yes, typically in `commonMain`. In an Android module - just inside `dependencies {}` block. The current way of documenting dependencies seems in line with the industry, e.g. take a look at [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines?tab=readme-ov-file#gradle). Do you have any suggestions for improvements?

> What about extensions-android?

Please note that (as [mentioned in the docs](https://arkivanov.github.io/Decompose/extensions/android/)) this experimental module is only for integration with classic Android views. You really need it, then it should go either under the `androidMain` in a KMP module, or just inside `dependencies {}` block in an Android module. Again, this looks in line with first-party open source docs.

> Following tutorials about navigation there is no file path included

There usually no particular file path, as it depends on the actual project, its structure and layout. Take a look at other examples in first-party libraries: [example 1](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#primitive-serializer) and [example 2](https://developer.android.com/topic/libraries/architecture/viewmodel#implement-viewmodel). How would like this to be improved?

> Also please include imports

This is indeed a good point. I will add all imports.

**Comment by zveljkovic** [comment]
Thank you for the quick response. What have you written explains it nicely. I will try to sort out my use case and I will make a PR with the proposed changes to documentation.

**Comment by zveljkovic** [comment]
I have opened a PR https://github.com/arkivanov/Decompose/pull/602/files
It is still work in progress but comments are welcome. Please close this issue.

**Comment by arkivanov** [comment]
Thanks! Let's keep this issue until all points are resolved, including imports that I'm going to fix.

**Comment by arkivanov** [comment]
I have added imports to all code snippets in the docs.

**Comment by arkivanov** [comment]
The docs has been improved. Feel free to reopen if there are still any issues or concerns. Thanks!
