### ISSUE TITLE
Animate predictive back cancellation

### ISSUE THREAD

**Issue by alexzhirkevich** [arkivanov/Decompose#618]
I can be doing something wrong, but currently, if predictive back gesture is cancelled, swipe progress instantly goes to 0. 
Can we have an animated current -> 0 like we have for current -> 1 when gesture is acknowledged?

**Comment by arkivanov** [comment]
Thanks, I will try to improve the animation.

**Comment by alexzhirkevich** [comment]
It's also would be awesome if we can configure [this hardcoded threshold](https://github.com/arkivanov/Decompose/blob/298b052ff4577ea8217d86084f1b9b11beb61470/extensions-compose/src/nonAndroidMain/kotlin/com/arkivanov/decompose/extensions/compose/stack/animation/predictiveback/PredictiveBackGestureOverlay.kt#L256) as well as `16.dp` gesture listener. Thanks.

**Comment by arkivanov** [comment]
Both changes will be available in the next alpha release.
