### ISSUE TITLE
build gets fail when i use extensionsComposeJetbrains = "2.2.2"

### ISSUE THREAD

**Issue by gulabsagevadiya** [arkivanov/Decompose#623]
works fine if i use below 
extensionsComposeJetbrains = "2.2.2-compose-experimental"
decompose= "2.2.2"

getting error if i use like below
extensionsComposeJetbrains = "2.2.2"
decompose= "2.2.2"

error log

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2.
Required by:
    project :composeApp
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 was found. The consumer was configured to find a library for use during 'kotlin-metadata', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' but:
  - Variant 'debugApiElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during compile-time:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'debugRuntimeElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during runtime:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'debugSourcesElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a component for use during runtime:
      - Incompatible because this component declares documentation, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'jvmApiElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during compile-time:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'jvmRuntimeElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during runtime:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'jvmSourcesElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a component for use during runtime:
      - Incompatible because this component declares documentation, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'metadataApiElements' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during 'kotlin-metadata':
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'metadataSourcesElements' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2:
      - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a library for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'releaseApiElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during compile-time:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'releaseRuntimeElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a library for use during runtime:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
  - Variant 'releaseSourcesElements-published' capability com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2 declares a component for use during runtime:
      - Incompatible because this component declares documentation, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
	at 

==============================================================================

BUILD FAILED in 6s
`

**Comment by arkivanov** [comment]
I think this works as expected. Please see the docs: https://arkivanov.github.io/Decompose/getting-started/installation/#extensions-for-jetpack-and-multiplatform-compose.

**Comment by gulabsagevadiya** [comment]
aah ok understood
