### ISSUE TITLE
Investigate if we can add checks to prevent passing the parent ComponentContext to children

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#635]
Maybe a compiler plugin. See the discussion: https://kotlinlang.slack.com/archives/C03H3N51SKT/p1707471641114349.

**Comment by art-shen** [comment]
It can also be a detekt/lint check.

Maybe a package with such checks can be useful for even for more recommendations, best practices, and warnings.
See [compose-rules](https://github.com/mrmans0n/compose-rules) as an example.

**Comment by arkivanov** [comment]
Couldn't come up with a decent solution with good protection and not too complex. Closing this for now.
