### ISSUE TITLE
Maintain the last remaining configuration in the stack if `popWhile` never returned `true`

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Decompose#640]
Current implementation of popWhile crashes the app if the predicate never returned true, because the resulting list of configurations would be empty:

```
inline fun <C : Any> StackNavigator<C>.popWhile(
    crossinline predicate: (C) -> Boolean,
    crossinline onComplete: (isSuccess: Boolean) -> Unit,
) {
    navigate(
        transformer = { stack -> stack.dropLastWhile(predicate) },
        onComplete = { newStack, oldStack -> onComplete(newStack.size < oldStack.size) },
    )
}
```

To match the behavior of `pop`, `popWhile` should maintain the last configuration in the stack if no match was found and leave the stack with a single element.

**Comment by arkivanov** [comment]
I guess it crashes if "the predicate never returned false", not "true". In other words, it crashes if the predicate always returns `true`.
