### ISSUE TITLE
KMP project stopped building for iOS with wasm supported decompose

### ISSUE THREAD

**Issue by anshulupadhyay03** [arkivanov/Decompose#658]
I have been running my knp project for android and iOS until i bumped my decompose version to decompose = "**3.0.0-alpha04**"
Below is the error i receive when i try to build the app for iOS. 

`> Task :shared:compileKotlinIosArm64 FAILED
e: Could not find "androidx.annotation:annotation" in [/Users/anshulupadhyay/Desktop/Android_projects/kmmMovieBuffGit/KmmMovieBuff, /Users/anshulupadhyay/.konan/klib, /Users/anshulupadhyay/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/anshulupadhyay/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_arm64]`

**Comment by arkivanov** [comment]
I don't think this is related to Decompose, but rather to Compose 1.6.x.

Please try adding `google()` repository in your Gradle configuration.

**Comment by anshulupadhyay03** [comment]
@arkivanov  Thanks for the reply. I have google() added to my gradle configuration. Why i think it is related to deompose because when I lower the version of decompose. Everything works fine. Also I face the same while building this project of other dev who i have some motivation for developing for wasm: https://github.com/mkonkel/GameShop

`enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental")
        maven("https://oss.sonatype.org/content/repositories/snapshots")
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental")
        maven("https://oss.sonatype.org/content/repositories/snapshots")
    }
}`

Als0 check my toml file below , i have further tried to bum the version to alpha6

`[versions]
coroutines = "1.7.2"
ktor = "2.3.0"
ktor-wasm = "3.0.0-wasm2"
androidx-activityCompose = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-core-ktx = "1.12.0"
imageLoading = "1.5.2"
decompose = "3.0.0-alpha06"
#essenty = "2.0.0-alpha02"
kotlinDateTime = "0.5.0"
compose = "1.5.4"
coil = "3.0.0-SNAPSHOT"
compose-plugin = "1.6.0-alpha01"
kotlin = "1.9.21"
agp = "8.2.1"


[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }

image-loading = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoading" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDateTime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-wasm" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor-wasm" }
ktor-client-web = { module = "io.ktor:ktor-client-js", version.ref = "ktor-wasm" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-wasm" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-wasm" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-wasm" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-wasm" }

#essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
arkivanov-decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
arkivanov-jetbrains-uiext = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }

#Image downloading
coil-coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor", version.ref = "coil" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }`

**Comment by arkivanov** [comment]
Decompose doesn't depend on `androidx.annotation:annotation` directly. Version `3.0.0-alpha04` depends on Compose `1.6.0-alpha01`, whereas Decompose `3.0.0-alpha03` depends on Compose `1.5.11`. You can also try updating Decompose to the latest version `3.0.0-alpha07` and Compose to `1.6.0-rc02`. If it doesn't solve the issue, please report a bug [here](https://github.com/JetBrains/compose-multiplatform/issues).

**Comment by arkivanov** [comment]
Looks related: https://github.com/JetBrains/compose-multiplatform/issues/4277

**Comment by anshulupadhyay03** [comment]
@arkivanov yes, this solves the issue. Thanks a lot .
