### ISSUE TITLE
Document compose BackHandler <> decompose backHandler <> predictive back interaction

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Decompose#662]
Currently, if a screen overrides BackHandler using the respective composable function, predictive back animation is disabled. Proposed solution is to document how users can avoid missing out on predictive back animations when writing their feature-screen level logic and using decompose. 

The best solution for such cases seems to be to only override back handler when the behavior of back  button is going to be custom, i.e.

```kotlin
    BackHandler(enabled = state is DisplayingSignInForm) { component.navigateBack() }
```

the solution above will only disable predictive back when the state is not the initial one.

**Comment by arkivanov** [comment]
Closed via 8b7c87f7.
