### ISSUE TITLE
Где посмотреть на реализацию CustomNavigationComponentChildren

### ISSUE THREAD

**Issue by FelixFalkovsky** [arkivanov/Decompose#688]
Из примеров которые даны в Simple не находит CustomNavigationComponentChildren ? Где его можно посмотреть ?

**Comment by arkivanov** [comment]
It's right there in samples: https://github.com/arkivanov/Decompose/blob/35f1e119eb1944af9fe0230cd862f49a64013fcc/sample/shared/shared/src/commonMain/kotlin/com/arkivanov/sample/shared/customnavigation/CustomNavigationComponent.kt#L20
