### ISSUE TITLE
ios Counter Example fails to build

### ISSUE THREAD

**Issue by Reedyuk** [arkivanov/Decompose#70]
When trying to build the ios counter example, i am getting an error:
```
ContentView.swift:14:81: error: cannot convert value of type '() -> CounterRootComponent' to expected argument type '(ComponentContext) -> CounterRootComponent'
    private var componentHolder = ComponentHolder(factory: CounterRootComponent.init)
```

<img width="953" alt="Screenshot 2022-04-11 at 09 32 22" src="https://user-images.githubusercontent.com/3853006/162697090-d6851ef5-64a9-4e42-b3da-bc07c18db29c.png">

I think i remember seeing something similar before and was to do with not including the decompose lib within the generate framework - maybe a red herring though

**Comment by arkivanov** [comment]
Thanks for raising, I will fix it ~~today~~ soon.

**Comment by Reedyuk** [comment]
```
    private var componentHolder = ComponentHolder {
        CounterRootComponent(componentContext: $0, deepLink: CounterRootComponentDeepLinkNone.shared, webHistoryController: nil)
    }
```

Can be resolved by doing this.
