### ISSUE TITLE
Update samples and templates

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#708]
Update Decompose version to 3.0.0:

- https://github.com/arkivanov/decompose-multiplatform-template
- https://github.com/arkivanov/decompose-dagger-sample

**Comment by malliaridis** [comment]
For [decompose-multiplatform-template](https://github.com/arkivanov/decompose-multiplatform-template) see https://github.com/arkivanov/decompose-multiplatform-template/pull/16.
