### ISSUE TITLE
Helpful tip for childSlot

### ISSUE THREAD

**Issue by longqingzhao** [arkivanov/Decompose#712]
I have an idea for this project.
when call childSlot in Dispatcher.IO before。check current Thread==''main''
This is helpful to resolve bug faster!

**Comment by arkivanov** [comment]
There are already main thread checks implemented. Could you please elaborate?

**Comment by longqingzhao** [comment]
You are right. But when I initialize a childStack in other thread unconsciously.

For example:
![IDmk2WbfzB](https://github.com/arkivanov/Decompose/assets/29787804/a523d597-bf0e-43a6-a15c-c2b841a92309)

1.When I call dialogNavigation.navigate { state }. It will be initialized in io coroutineScope and throw error about check main thread
 ![igk8vciETU](https://github.com/arkivanov/Decompose/assets/29787804/3481fc84-2e82-4987-a90a-320725d02da5)

2.When I call dialogNavigation.navigate { state }. It will be initialized in UI coroutineScope and my app closed with nothing error.
![vooVcedJ5L](https://github.com/arkivanov/Decompose/assets/29787804/81ded64f-b8b3-4b63-993c-cc1dc5df608f)
![IwvEqusnTe](https://github.com/arkivanov/Decompose/assets/29787804/35f1d8b1-16f7-48b0-85a8-75e78592ca8d)

When I initialize childStack by these error way,I need to analysis source code and debug.

If check main thread for here,I can know the cause first. It's friendly for some developer.

![20240510-085507](https://github.com/arkivanov/Decompose/assets/29787804/55248620-e0f2-4058-8b3b-c38e0e5a2282)

**Comment by arkivanov** [comment]
Perhaps, we could an additional main thread check. 

Btw, your first code snippet has a mistake. Please don't use `get() =` for navigation properties, just assign the value directly `val state: Value<ChildSlot<...>> = childSlot(...)`.

**Comment by arkivanov** [comment]
Sorry but I still don't see where is the issue in your case. The case #1 has the main thread check already and prints the error in the logs because of the background thread. The case #2 has the main thread check as well and should work correctly because of the main thread.

**Comment by longqingzhao** [comment]
In case #1, I indeed have a main thread check and an error message is thrown. However, the error message did not specifically mention that val state: Value<ChildSlot<...>> = childSlot(...) cannot be used on a background thread.
 I spent a long time searching for the issue and trying out various solutions before realizing that my val state: Value<ChildSlot<...>> = childSlot(...) was being executed on a background thread.

The problem is that while there is a main thread check, it does not explicitly indicate that childSlot must be run on the main thread in error.

Therefore, I suggest that a main thread check should be performed inside the childSlot method and an exception should be thrown accordingly. This would be very user-friendly.

**Comment by arkivanov** [comment]
Ok, so the actual issue is because the property is accessed on a background thread. It makes sense to add the additional check. Thanks for raising.

**Comment by arkivanov** [comment]
@longqingzhao Turned out there is already a main thread check since version [3.0.0-alpha07](https://github.com/arkivanov/Decompose/releases/tag/3.0.0-alpha07). It's [here](https://github.com/arkivanov/Decompose/blob/a0b042ec22f1cba6844e654d73ef6cd05d34388d/decompose/src/commonMain/kotlin/com/arkivanov/decompose/router/children/ChildrenFactory.kt#L159), that line is also called on initialization, so there should be a proper stack trace in the logs.

Could you please confirm what version you were using? I think I'm going to revert the recent change (#716), as there is no reason for two checks one by one.

**Comment by longqingzhao** [comment]
The library com.arkivanov.decompose:3.0.0 you're using does indeed have main thread checks in some places, but as you've pointed out, the checks may not be explicit enough for all scenarios. While using dialogNavigation.navigation { state } on a background thread might trigger a main thread check, there's no direct and explicit mention of the same for childSlot methods.

As you suggested, using val state: Value<ChildSlot<...>> = childSlot(...) directly instead of a setter like get()= is preferred. However, if this initialization happens on a background thread, it could still pose problems. Therefore, not only does the documentation need to be more explicit about these threading considerations, but the code itself could also benefit from additional checks or annotations to indicate the intended usage.

**Comment by arkivanov** [comment]
If you call `childSlot` on a background thread, the check I linked should print a proper message in the logs with a stack trace pointing to the call site. Since `childSlot` calls `children`, which has the check. There should be a message like "Expected to be called on the main thread, but was [thread name]" with a stack trace.

I will also update the docs, thanks.
