### ISSUE TITLE
Support forward navigation

### ISSUE THREAD

**Issue by oblakr24** [arkivanov/Decompose#728]
Perhaps this is in some way already supported and for sure I can try to do it myself via a duplicate reverse stack - but it would be good to add something like `BiDirectionalStackNavigator` and add a `BiDirectionalStackNavigator.next()` extension. 

The bi-directional navigator would maintain a stack of forward navigation steps everytime it is popped, and every time a new step is pushed, the forward navigation stack is cleared.

This would be mainly useful for web where forward presses could be intercepted.

I checked https://arkivanov.github.io/Decompose/navigation/stack/browser-history/ but am not sure if this is 100% the same (also the [link](https://github.com/arkivanov/Decompose/blob/master/decompose/src/jsMain/kotlin/com/arkivanov/decompose/router/stack/webhistory/DefaultWebHistoryController.kt) is broken).

**Comment by arkivanov** [comment]
I'm not sure if I understand the issue.

`WebHistoryController` already supports the forward navigation. You can `push` a few components to the stack, then you can press the Back button in the browser, and then you should be able to press the Forward button and it should be handled correctly (i.e. the previously popped component pushed again).

If you want to navigate forward in the code, you can just `push` whatever configuration you need.

> the link is broken

Thanks! I've fixed the broken link.

**Comment by oblakr24** [comment]
Amazing, after checking the samples on the updated links, this solves my use-case. Thank you!
