### ISSUE TITLE
IllegalStateException: Another supplier is already registered with the key

### ISSUE THREAD

**Issue by 658jjh** [arkivanov/Decompose#739]
Hi team, 
I am getting this error when trying to create a new child from a `Component`.
My app structure looks like this:

Root -> screen A, B, C, D
Screen A -> screen A1 , A2 
Screen B -> screen B1, B2

Screen A1 -> create child stacks: A11 and A12 --> This is where I got the error.
I tried to use both `ChildStack` and `ChildSlot` but they got the same error.
Does it because the stack is too deep? 
I can use `A11` and `A12` as childs of Screen A same as Screen `A1` and `A2` but it not what I'm expected. 
Do we have any solution for this?
Thank you!

**Comment by arkivanov** [comment]
Please see the FAQ section here: https://arkivanov.github.io/Decompose/faq/#error-another-supplier-is-already-registered-with-the-key

If you are still having the problem, it would be nice to have a reproducer project that I could run.

**Comment by 658jjh** [comment]
Here is the reproducer project @arkivanov 

[KotlinProject.zip](https://github.com/user-attachments/files/16313476/KotlinProject.zip)

**Comment by arkivanov** [comment]
After looking at the source code, you are not following the docs. Specifically, you integrated your `AppComponent` in the `MainActivity` incorrectly. The FAQ section I've linked above contains the following:

<img width="685" alt="image" src="https://github.com/user-attachments/assets/08091e99-f18f-4318-aa21-5137e99e9cb2">

Could you please try fixing that?

Another issue is that you are creating child components in your Composable functions, e.g. in `AScreen`. This is also incorrect. You can just take the component instances from the stack.

Here is the patch that should fix the crash.

```diff
Index: composeApp/src/commonMain/kotlin/a/AScreen.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/composeApp/src/commonMain/kotlin/a/AScreen.kt b/composeApp/src/commonMain/kotlin/a/AScreen.kt
--- a/composeApp/src/commonMain/kotlin/a/AScreen.kt	(revision da0bcc5200a7c95164c99bf8e9bdb42faa513808)
+++ b/composeApp/src/commonMain/kotlin/a/AScreen.kt	(date 1721401075251)
@@ -50,9 +50,9 @@
         stack = component.childStack, animation = stackAnimation(slide())
       ) { child ->
         when (val instance = child.instance) {
-          is MainScreen.A1 -> A1Screen(A1Component(instance.component))
-          is MainScreen.A2 -> A2Screen(A2Component(instance.component))
-          is MainScreen.A3 -> A3Screen(A3Component(instance.component))
+          is MainScreen.A1 -> A1Screen(instance.component)
+          is MainScreen.A2 -> A2Screen(instance.component)
+          is MainScreen.A3 -> A3Screen(instance.component)
         }
       }
     }
Index: composeApp/src/androidMain/kotlin/org/example/project/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/composeApp/src/androidMain/kotlin/org/example/project/MainActivity.kt b/composeApp/src/androidMain/kotlin/org/example/project/MainActivity.kt
--- a/composeApp/src/androidMain/kotlin/org/example/project/MainActivity.kt	(revision da0bcc5200a7c95164c99bf8e9bdb42faa513808)
+++ b/composeApp/src/androidMain/kotlin/org/example/project/MainActivity.kt	(date 1721401099426)
@@ -13,8 +13,8 @@
   override fun onCreate(savedInstanceState: Bundle?) {
     super.onCreate(savedInstanceState)
 
-    setContent {
-      val appComponent = AppComponent(defaultComponentContext())
+    val appComponent = AppComponent(defaultComponentContext())
+    setContent {
       App(appComponent)
     }
   }
```

**Comment by 658jjh** [comment]
Oh, I am sorry @arkivanov 
It was the quick reproducer so the AScreen is wrong., it should be like what you said.
The one that I want to mention is in A11Screen, when you click open A12 and open A13
[KotlinProject.zip](https://github.com/user-attachments/files/16314498/KotlinProject.zip)

**Comment by arkivanov** [comment]
That's a different issue:

```
java.lang.ClassCastException: a.child.a1.child.A1Destination$A13 cannot be cast to AppDestination
```

This happens because you are using Koin to inject `StackNavigation`. I think Koin doesn't support generic types, so it injects incorrect instances. I recommend to either use manual DI, or a compile time safe DI framework like Dagger (Android) or kotlin-inject (KMP). As of `StackNavigation`, there is no need to use DI framework for that. Just create it as usual.

```
private val navigation = StackNavigation<A1Destination>()
```

**Comment by 658jjh** [comment]
I am so sorry again @arkivanov, my bad.
I try again with the reproducer app. And it works fine even I added many childs. 
But with the same idea for my real project I got the issue. :( 
[KotlinProject copy.zip](https://github.com/user-attachments/files/16322013/KotlinProject.copy.zip)

**Comment by arkivanov** [comment]
This is again due to the issue I mentioned earlier:

> Another issue is that you are creating child components in your Composable functions, e.g. in AScreen. This is also incorrect. You can just take the component instances from the stack.

It's not allowed to share an instance of `ComponentContext` between multiple component instances. I suggest to read through the docs carefully (at least the [Quick Start](https://arkivanov.github.io/Decompose/getting-started/quick-start/) section) and also refer to [samples](https://github.com/arkivanov/Decompose/tree/master/sample).

Here is the patch.

```diff
Index: composeApp/src/commonMain/kotlin/ui/add_budget/AddBudgetScreen.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/composeApp/src/commonMain/kotlin/ui/add_budget/AddBudgetScreen.kt b/composeApp/src/commonMain/kotlin/ui/add_budget/AddBudgetScreen.kt
--- a/composeApp/src/commonMain/kotlin/ui/add_budget/AddBudgetScreen.kt	(revision e22287ea1d82e1b5560b94021c2e789e4ab8f83b)
+++ b/composeApp/src/commonMain/kotlin/ui/add_budget/AddBudgetScreen.kt	(date 1721504728021)
@@ -33,11 +33,11 @@
       animation = stackAnimation(slide())
     ) { child ->
       when (val instance = child.instance) {
-        is AddBudgetScreen.Main -> AddBudgetMainScreen(AddBudgetMainComponent(instance.component, instance.component.addBudgetNavigation, component.mainAction))
-        is AddBudgetScreen.Envelope -> EnvelopeScreen(EnvelopeComponent(instance.component, instance.component.addBudgetNavigation))
-        is AddBudgetScreen.FiftyTwentyThirty -> FiftyTwentyThirtyRootScreen(FiftyTwentyThirtyRootComponent(instance.component, instance.component.addBudgetNavigation, component.mainAction))
-        is AddBudgetScreen.PayYourselfFirst -> PayYourselfFirstScreen(PayYourselfFirstComponent(instance.component, instance.component.addBudgetNavigation))
-        is AddBudgetScreen.SixtyPercent -> SixtyPercentScreen(SixtyPercentComponent(instance.component, instance.component.addBudgetNavigation))
+        is AddBudgetScreen.Main -> AddBudgetMainScreen(instance.component)
+        is AddBudgetScreen.Envelope -> EnvelopeScreen(instance.component)
+        is AddBudgetScreen.FiftyTwentyThirty -> FiftyTwentyThirtyRootScreen(instance.component)
+        is AddBudgetScreen.PayYourselfFirst -> PayYourselfFirstScreen(instance.component)
+        is AddBudgetScreen.SixtyPercent -> SixtyPercentScreen(instance.component)
       }
     }
   }
```
