### ISSUE TITLE
Compose Multiplatform resources via WebHistoryController

### ISSUE THREAD

**Issue by nevrozza** [arkivanov/Decompose#742]
Hi! Is there way to use Compose Multiplatform resources with WebHistoryController?
Example of problem:
I have custom font. 
Ip without WebHistoryController: http://localhost:8080/
With: http://localhost:8080/auth/activation It causes problem: `Cannot GET /auth/composeResources/pansion.common.utils_compose.generated.resources/font/Geologica-Black.ttf` ("/auth" is unnecessary).

**Comment by arkivanov** [comment]
This issue looks unrelated to `WebHistoryController`, but rather a general Compose issue. I recommend askin in Kotlin Slack, filing an issue in [YouTrack](https://youtrack.jetbrains.com/), or asking in [Compose Multiplatform Discussions](https://github.com/JetBrains/compose-multiplatform/discussions).

**Comment by nevrozza** [comment]
@arkivanov Thanks for ur answer!
