### ISSUE TITLE
Disallow clicks for either of stack destinations while the iOS's PredictiveBackOverlay gesture is in progress.

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Decompose#773]
Currently, while an iOS back gesture slide is active, both screens are clickable. This causes issues with lifecycles of screens that are being transitioned. We could investigate into a better lifecycle for predictive back animated children or disallow interactions while predictive back overlay gesture is active.

**Comment by arkivanov** [comment]
Decompose provides the `disableInputDuringAnimation` flag to control this behaviour for both the [old](https://github.com/arkivanov/Decompose/blob/ba105fda4e26e01171098787ed3b9733176e1d1a/extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/stack/animation/StackAnimation.kt#L34) and [new](https://github.com/arkivanov/Decompose/blob/ba105fda4e26e01171098787ed3b9733176e1d1a/extensions-compose-experimental/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/experimental/stack/animation/StackAnimation.kt#L36) animation APIs. The default value is `true` meaning that all input events are disabled during stack change animations. Are you using another library on top of Decompose, like `decompose-router`?

**Comment by Nek-12** [comment]
I'm not using a non-default value

Are you sure this parameter is working for iOS's [PredictiveGestureOverlay](https://github.com/arkivanov/Decompose/blob/ba105fda4e26e01171098787ed3b9733176e1d1a/extensions-compose/src/nonAndroidMain/kotlin/com/arkivanov/decompose/extensions/compose/stack/animation/predictiveback/PredictiveBackGestureOverlay.kt)?

<img width="905" alt="image" src="https://github.com/user-attachments/assets/91b57818-b174-47b9-a643-5aad157e3b63">

**Comment by arkivanov** [comment]
This parameter is for stack animations, not the overlay. Should be working for all platforms.

**Comment by Nek-12** [comment]
As per the video I sent in the chat, with the default configuration from the documentation it isn't

**Comment by arkivanov** [comment]
I will try checking on iOS as well. This might be a bug in Compose for iOS or something. Assuming you are not using any library that wraps Decompose.

**Comment by arkivanov** [comment]
Thanks for reporting! This is indeed a bug in the predictive back gesture animation. I will fix it. The new experimental animation API is not affected.
