### ISSUE TITLE
Incomplete documentation on Compose-JB usage

### ISSUE THREAD

**Issue by darvld** [arkivanov/Decompose#78]
When using Decompose with Compose-JB for desktop, it is necessary to use the `LifecycleController` composable, otherwise the `LifecycleRegistry` will not work properly. However, this is not mentioned in the documentation at all (even if the samples do include it in the code). I believe this fact should be clarified in the documentation.
(If none of this is actually necessary and I'm simply missing something obvious, please let me know.)

**Comment by arkivanov** [comment]
Indeed, thanks for raising!

Actually in many cases you can just call `lifecycle.resume()` after creating the root. Of course it won't signal when the window is minimised/restored, but it's not necessarily needed.
