### ISSUE TITLE
Predictive back gesture animation not working when custom BackCallback registered

### ISSUE THREAD

**Issue by rsktash** [arkivanov/Decompose#799]
I've a master detail UI
Master component shows list of items
Details component shows selected item for editing
In the Details component before navigating back it checks if the editing data has any change
If data has changed a dialog will be shown in order to get confirmation from user about data loss on navigating back

![telegram-cloud-photo-size-2-5226465945415967630-y](https://github.com/user-attachments/assets/be64dae8-6a9a-49ff-9091-038164f4a069)

If I comment this code animation works

**Comment by arkivanov** [comment]
Do you mean that the callback is registered in the child component? If so, then this is by design. You should disable the callback (set `callback.enabled = false`) when the confirmation is not required.

**Comment by arkivanov** [comment]
Usually the dialog should be shown from the callback.

**Comment by rsktash** [comment]
Yes, It's registered in a child component
I've tested with `subscribe { backCallback.isEnabled = doWeNeedConfirmation }`
Unfortunately it didn't change the behavior

**Comment by arkivanov** [comment]
If you set enabled = false, then the animation should work. It would be nice to have a reproducer of the issue.

**Comment by rsktash** [comment]
I've tested with minimal reproducer and it's working
The issue was originating from a full screen dialog used for EditComponent

**Comment by rsktash** [comment]
I'm using navigation suite and panels
I tried to prevent user clicks on navigation buttons while editing an item
Is there a way to temporarily switch panel mode to single?

**Comment by rsktash** [comment]
OK. I've created base component and extension function in order to control panel mode

![telegram-cloud-photo-size-2-5226773263210900364-y](https://github.com/user-attachments/assets/e74e805b-b847-42c2-86be-af7ff8ee129d)

**Comment by arkivanov** [comment]
You should be able to just not navigation if the edit mode is active. Just add a condition somewhere in your components.
