### ISSUE TITLE
 kotlinx-serialization: 1.6.3, why not 1.7.3 ?

### ISSUE THREAD

**Issue by Shabinder** [arkivanov/Decompose#800]
couple of past releases have been shipped with 1.6.3 serialization, is there a blocker in updating to latest ?

**Comment by arkivanov** [comment]
I'm not aware of any blockers. But the newer versions should be backward compatible, I guess. Why would you want an update?

**Comment by Shabinder** [comment]
I just updated, yup its backward compatible, no hurry, just wanted to give a headsup.

**Comment by arkivanov** [comment]
Thanks!
