### ISSUE TITLE
A small issue regarding modular architecture

### ISSUE THREAD

**Issue by pawarbhushan08** [arkivanov/Decompose#814]
Cannot access 'com. arkivanov. decompose. Child' which is a supertype of 'com. arkivanov. decompose. Child. Created'. Check your module classpath for missing or conflicting dependencies

I am quite sure that  the my gradle dependencies are perfectly provided. If I move this class to another package, it works fine.

![image](https://github.com/user-attachments/assets/9a9337d2-1e67-41cf-bbb5-f9b8be0ec1ba)

**Comment by arkivanov** [comment]
This is either a bug in the IDE or you need to add a dependency on `com.arkivanov.decompose:decompose`. Without a reproducer it's hard to say for sure.

**Comment by pawarbhushan08** [comment]
Never seen such a quick reply on any other Library issue. Thank you so much. issue is resolved by adding extra dependency of com.arkivanov.decompose:decompose in my module.
