### ISSUE TITLE
Predictive Back Gesture understanding

### ISSUE THREAD

**Issue by kopylovis** [arkivanov/Decompose#829]
Hi @arkivanov. 
First of all, thank you very much for the work you do.

I encountered the fact that I can not implement predictive gestures in my app, at least on Android target. I am testing on the Pixel 9 with Android 15.

navgraph is approximately the same as in the diagram.
![image](https://github.com/user-attachments/assets/4df10ad0-7068-41c4-9ccb-654dc2237c64)
Conventionally, being on the TabComponent, I open the settings or about, which is a child of the root component, in which the predictive is configured, according to [the documentation](https://arkivanov.github.io/Decompose/extensions/compose/#predictive-back-gesture) and when navigating back, the animation does not occur. Custom BackCallback is not present in children for the sake of purity of the experiment. 
In the root content:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/d03f31f3-e3f6-4979-904f-1bdc1a8c3595" />

**Comment by arkivanov** [comment]
What Android version you are trying it on? Have you enabled it in the manifest file? See: https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#opt-predictive

**Comment by kopylovis** [comment]
omg, that was the reason :face_palm:
thank you
